.TH "geohfree" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBgeohfree\fP - free all left over parts of a GEO header
.SH SYNOPSIS
.sp
.nf
.ft CR
     #include "geoh.h"

     int
geohfree(
     	GEOH_T **geohpp,
	int      nbands)

.ft R
.fi
.SH DESCRIPTION
.PP
\fBgeohfree\fP frees an entire geohpp structure.
.SH RETURN VALUE
.sp
.nf
.ft CR
     OK for success, ERROR for failure
.ft R
.fi
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
