CATEGORY := mapproj
DESCRIPTION := map projections

FUNCS := get_proj_id get_proj_name get_proj_units pack_dms read_proj unpack_dms

PRIVATE_SRCS := 

INCLUDE_FILES := mapproj.h

include $(IPW)/make/funcCategory
