NAME := stropts
DESCRIPTION := string options

DIRS := main

#  Because the functions in this library have the same names has their
#  counterparts in the standard IPW library "libipw", they don't have
#  man pages (because their man pages would overwrite the man pages
#  of their counterparts).
#
#  Therefore, only the HTML version of the function list is created,
#  and it just has the description of the library.

NO_FUNCS_IN_LIST := 1

include $(IPW)/make/library
