.TH "mnxfp" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBmnxfp\fP - minima and maxima of fpixel vectors
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "fpio.h"

int
mnxfp(
	fpixel_t   *x,		|* multiplexed vectors		 *|
	int         npixv,	|* length of vectors		 *|
	int         nbands,	|* # multiplexed bands		 *|
	fpixel_t   *mmval)	|* min,max values		 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBmnxfp\fP finds the minima and maxima of the nbands interleaved
vectors of length npixv and of type fpixel_t.  The minima and
maxima of the bands are interleaved, i.e. the minimum and
maximum of band n are in mmval[2*n] and mmval[2*n+1].
.PP
\fBmnxfp\fP is normally used with the fpio package to find the
parameters necessary to write the floating-point pixels as
pixel_t's.
.PP
If the returned pointer "mmval" is used as an argument to lqhmake, it
must first be tested to see if the values are equal.  The following
code should follow a call to \fBmnxfp\fP that will be used this way:
.sp
.nf
.ft CR
	if (parm.mmval[0] == parm.mmval[1]) {
		parm.mmval[1] += 1;
	}
.ft R
.fi
.SH RETURN VALUE
.PP
OK (for backward compatibility)
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
