.TH "units_match" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBunits_match\fP - check if a string matches a units id
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "units.h"

int
units_match(
	char	  *string,	|* string to test 		*|
	UNITS_T    id)		|* units id 			*|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBunits_match\fP determines if a given \fIstring\fP matches a units \fIid\fP.
The string matches if it is the same string that the function
"units_as_str" returns for the given id.  \fBunits_match\fP also
accepts variations for the string depending upon the id.
.SH RETURN VALUE
.PP
1 is returned if the string matches the id.  Otherwise, 0 is returned.
.SH EXAMPLES
.sp
.nf
.ft CR
	units_match("mm", U_METERS)		returns 0
	units_match("m", U_METERS)		returns 1
	units_match("meters", U_METERS)		returns 1
	units_match("Meters", U_METERS)		returns 1
	units_match("METERS", U_METERS)		returns 1
.ft R
.fi
.SH GLOBALS ACCESSED
.PP
_unitStrings
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.TP
Nov 1995
	Written by J. Domingo, OSU
.SH BUGS
.PP
None.
.SH SEE ALSO
