.TH "heat_stor" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBheat_stor\fP - calculates change in heat storage in a layer
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "envphys.h"

double
heat_stor(
     double  cp,        /* specific heat of layer (J/kg/K) */
     double  spm,       /* layer specific mass (kg/m^2)    */
     double  tdif)      /* temperature change (K)          */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBheat_stor\fP calculates the change in heat storage in a
homogeneous layer as a function of the change in average layer temperature.
.PP
The layer's specific mass (the argument \fIspm\fP) can be computed
by multiplying the layer's thickness (m) by its density (kg/m^3).
.SH RETURN VALUE
.PP
heat storage  (J/m^2)
.SH HISTORY
.TP
Aug 1984
written by D. Marks, CSL (GSFC), UCSB;
.sp
.TP
May 1995
Ported from QDIPS to IPW.  J. Domingo, OSU.
