.TH "budyer" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBbudyer\fP - heat exchanges using Businger-Dyer model
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "envphys.h"

int
budyer(
     double  z,    /* upper height of wind speed & temp measurement (m) */
     double  z0,   /* lower height of wind speed & temp measurement (m),
                      (maybe roughness length)                          */
     double  t,    /* temperature at z (K)                              */
     double  t0,   /*      "      "  z0 (K)                             */
     double  e,    /* vapor pressure at z (Pa)                          */
     double  e0,   /*   "      "     "  z0 (Pa)                         */
     double  u,    /* wind speed at z (m/s)                             */
     double  u0,   /*  "     "   "  z0 (m/s)                            */
     double  p,    /* pressure (Pa)                                     */

    /* output variables */

     double  *h,   /* sensible heat exchange (W/m^2)                    */
     double  *le)  /* latent heat exchange (W/m^2)                      */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBbudyer\fP calculates sensible and latent heat exchanges using
the Businger-Dyer model for turbulent transfer.  See chapter 6 of the
reference below.
.SH RETURN VALUE
.sp
.nf
.ft CR
     OK      all calculations successfully completed.

     ERROR   either argument \fIe\fP or \fIe0\fP exceeds saturation vapor
             pressure at the appropriate temperature (the
             function fixes the erroneous value(s), issues
             a warning message, and proceeds with the
             calculations).
.ft R
.fi
.SH HISTORY
.TP
Jun 1995
Converted from QDIPS to IPW by J. Domingo, OSU
.SH SEE ALSO
.PP
Fleagle 1980
.br
