.TH "error" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBerror\fP - print error message and exit
.SH SYNOPSIS
.sp
.nf
.ft CR
void error(format, arg, ...)
char *format;
{type} arg; ...

.ft R
.fi
.SH DESCRIPTION
.PP
Error prints the \fBerror\fP message described by the printf-style "format"
and "args" on the standard \fBerror\fP output.  If usrerr() has been called,
its argument is also printed.  If syserr() has been called, a UNIX
system \fBerror\fP message is also printed.
.SH RETURN VALUE
.PP
None.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
