.TH "sathdup" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBsathdup\fP - duplicate an IPW SATH header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "sath.h"

SATH_T **
sathdup(
	SATH_T        **oldhpp,	  |* -> old SATH array	 	*|
	int             nbands)	  |* # header bands		*|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBsathdup\fP creates a duplicate of the IPW SATH header pointed to by
"oldhpp".
.PP
\fBsathdup\fP is an easy way for applications programs to create a new SATH
(e.g., for an output image, after having read the SATH for an input
image).
.SH RETURN VALUE
.PP
A pointer to the duplicate header is returned.  NULL is returned if
an error occurs.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
