################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/samples/command \
src/lib/libtopo/topo \
src/lib/libstropts/main \
src/lib/libsnobal/snobal \
src/lib/libmodel/solar \
src/lib/libmodel/snow \
src/lib/libmodel/radiation \
src/lib/libmodel/radiation/Dozier \
src/lib/libmodel/envphys \
src/lib/libipw/winh \
src/lib/libipw/util \
src/lib/libipw/units \
src/lib/libipw/uio \
src/lib/libipw/sunh \
src/lib/libipw/strvec \
src/lib/libipw/skewh \
src/lib/libipw/sath \
src/lib/libipw/pixio \
src/lib/libipw/orh \
src/lib/libipw/math \
src/lib/libipw/math/mvalloc \
src/lib/libipw/mapproj \
src/lib/libipw/main \
src/lib/libipw/lqh \
src/lib/libipw/horh \
src/lib/libipw/hdrio \
src/lib/libipw/gethdrs \
src/lib/libipw/geoh \
src/lib/libipw/fpio \
src/lib/libipw/error \
src/lib/libipw/datetime \
src/lib/libipw/crh \
src/lib/libipw/bih \
src/lib/libimage/mask \
src/lib/libimage/image \
src/lib/libimage/error \
src/lib/libgctp/gctp \
src/bin/transform/zoom \
src/bin/transform/window \
src/bin/transform/wedge \
src/bin/transform/transpose \
src/bin/transform/skew \
src/bin/transform/resamp \
src/bin/transform/flip \
src/bin/transform/fillbands \
src/bin/transform/edimg \
src/bin/transform/dither \
src/bin/transform/convolve \
src/bin/topocalc/viewf/viewcalc \
src/bin/topocalc/shade \
src/bin/topocalc/pmask \
src/bin/topocalc/horizon/hor1d \
src/bin/topocalc/gshade \
src/bin/topocalc/gradient \
src/bin/topocalc/ghorizon \
src/bin/topocalc/ggradient \
src/bin/topocalc/deltaz \
src/bin/topocalc/bmask \
src/bin/stats/mstats \
src/bin/stats/lutx \
src/bin/stats/istatrel \
src/bin/stats/ipwinterp \
src/bin/stats/imgstat \
src/bin/stats/hist \
src/bin/stats/cnhist.all \
src/bin/rad.pt/twostream \
src/bin/rad.pt/trad_can \
src/bin/rad.pt/trad \
src/bin/rad.pt/thermin \
src/bin/rad.pt/sunlight \
src/bin/rad.pt/sunang \
src/bin/rad.pt/solar_can \
src/bin/rad.pt/solar \
src/bin/rad.pt/cloud \
src/bin/rad.glb/gtoporad \
src/bin/rad.glb/gsunweights \
src/bin/rad.glb/gsunlight \
src/bin/rad.glb/gelevrad \
src/bin/rad.bas/topotherm \
src/bin/rad.bas/toporad \
src/bin/rad.bas/th_adj \
src/bin/rad.bas/tcloud \
src/bin/rad.bas/elevrad \
src/bin/rad.bas/cf_cloud \
src/bin/proj/transcoord \
src/bin/proj/reproj_area \
src/bin/proj/reproj \
src/bin/proj/mkproj \
src/bin/pixcalc/scale \
src/bin/pixcalc/normalize \
src/bin/pixcalc/ninterp \
src/bin/pixcalc/mult \
src/bin/pixcalc/lincom \
src/bin/pixcalc/itrim \
src/bin/pixcalc/imgsum \
src/bin/pixcalc/imath \
src/bin/pixcalc/iinterp \
src/bin/pixcalc/iadd \
src/bin/pixcalc/despike \
src/bin/pixcalc/bitcom \
src/bin/physmod.spat/wbal \
src/bin/physmod.spat/mkprecip \
src/bin/physmod.spat/itrbxfr \
src/bin/physmod.spat/isnobal \
src/bin/physmod.spat/iptx \
src/bin/physmod.spat/ipmx \
src/bin/physmod.pt/trbxfr \
src/bin/physmod.pt/trb_Ri \
src/bin/physmod.pt/srftmp \
src/bin/physmod.pt/soiltmp \
src/bin/physmod.pt/snowmass \
src/bin/physmod.pt/snobal \
src/bin/physmod.pt/ptx \
src/bin/physmod.pt/ptaylorx \
src/bin/physmod.pt/pmx \
src/bin/physmod.pt/penmanx \
src/bin/physmod.pt/mkpcp_a \
src/bin/physmod.pt/mkpcp \
src/bin/physmod.pt/humidx \
src/bin/physmod.pt/gsnow \
src/bin/physmod.pt/bowvap \
src/bin/physmod.pt/advec \
src/bin/phys.spat/isatvp \
src/bin/phys.spat/irh2vp \
src/bin/phys.spat/ipott \
src/bin/phys.spat/indvi \
src/bin/phys.spat/idewpt \
src/bin/phys.spat/ialbedo \
src/bin/phys.spat/deltaT \
src/bin/phys.pt/zpr \
src/bin/phys.pt/wbt \
src/bin/phys.pt/vptr \
src/bin/phys.pt/vp2sph \
src/bin/phys.pt/swp \
src/bin/phys.pt/swe \
src/bin/phys.pt/svp_slope \
src/bin/phys.pt/sling \
src/bin/phys.pt/satvp \
src/bin/phys.pt/rh2vp \
src/bin/phys.pt/refdx \
src/bin/phys.pt/pott \
src/bin/phys.pt/mse \
src/bin/phys.pt/glob.alb \
src/bin/phys.pt/dewpt \
src/bin/phys.pt/albedo \
src/bin/phys.pt/ah2vp \
src/bin/numeric/weights \
src/bin/numeric/smooth \
src/bin/numeric/seq \
src/bin/numeric/random \
src/bin/numeric/qdint \
src/bin/numeric/ezint \
src/bin/numeric/akintrp \
src/bin/lq/requant \
src/bin/lq/pix2fp \
src/bin/lq/lqmm \
src/bin/lq/lqhx \
src/bin/import/text2ipw \
src/bin/import/text2bin \
src/bin/import/surface \
src/bin/import/pbm2ipw \
src/bin/import/msurfprep \
src/bin/import/msurface \
src/bin/import/dem2ipw \
src/bin/import/crossval \
src/bin/header/rmhdr \
src/bin/header/mkwinh \
src/bin/header/mksunh \
src/bin/header/mksath \
src/bin/header/mklqh \
src/bin/header/mkgeoh \
src/bin/header/mkcrh \
src/bin/header/mkbih \
src/bin/export/ipw2xim \
src/bin/export/ipw2sun \
src/bin/export/ipw2ps \
src/bin/export/ipw2ppm \
src/bin/export/ipw2pgm \
src/bin/export/ipw2pbm \
src/bin/export/ipw2hds \
src/bin/export/ipw2bin \
src/bin/export/bin2text \
src/bin/datetime/cvtime \
src/bin/datetime/cmptime \
src/bin/datetime/addtime \
src/bin/climate/proport \
src/bin/climate/hcnx \
src/bin/classify/declass \
src/bin/classify/classify \
src/bin/classify/classeq \
src/bin/basic/primg \
src/bin/basic/poly \
src/bin/basic/mux \
src/bin/basic/ipwfile \
src/bin/basic/demux \

