CATEGORY := sath
DESCRIPTION := satellite headers

FUNCS := sathdup sathmake sathread sathwrite

PRIVATE_SRCS := _sathcheck.c

INCLUDE_FILES := sath.h

include $(IPW)/make/funcCategory

_sathcheck.o sathdup.o sathread.o sathwrite.o : _sath.h
