.TH "sampsize" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBsampsize\fP - compute total
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "bih.h"

int
sampsize(
	int		fd)	|* file descriptor		 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBsampsize\fP computes the total number of bytes per sample in the image
associated with the file descriptor fd
.SH RETURN VALUE
.PP
total # bytes per image sample
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
