.TH "crhsort" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBcrhsort\fP - return a copy of classes sorted by class number
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "crh.h"

int
crhsort(
	CRH_T   *crhp,		|* -> CRH for a specific band	    *|
	int	 sortkey)	|* = SORT_BY_CLASS or SORT_BY_RANGE *|

.ft R
.fi
.SH DESCRIPTION
.sp
.nf
.ft CR
     crhsort sorts the given CRH header according to the given sort key:
.ft R
.fi
.PP
SORT_BY_CLASS or SORT_BY_RANGE.
.PP
\fBcrhsort\fP is called by IPW application programs to sort the CRH
header by class number or by range.
.SH RETURN VALUE
.PP
OK for success, ERROR for failure
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
