.TH "urskip" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBurskip\fP - skip input on UNIX file descriptor
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

long
urskip(
	int      fd,		|* input file descriptor	 *|
	long     nbytes)	|* #bytes to skip		 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBurskip\fP causes nbytes bytes of input on fd to be skipped.
nbytes must be > 0 (i.e., only forward skips are allowed).
.PP
Use \fBurskip\fP instead of the UNIX system call lseek to skip input data.
.SH RETURN VALUE
.PP
>= 0	number of bytes skipped
.PP
ERROR	for failure
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_uiocb
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
