.TH "hdralloc" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBhdralloc\fP - allocate an IPW image header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "hdrio.h"

addr_t
hdralloc(
	int             n,
	int             size,
	int             fd,
	const char     *name)

.ft R
.fi
.SH DESCRIPTION
.PP
\fBhdralloc\fP allocates a n objects of size bytes each.  If the allocation
fails, then "name" and "fd" (if not equal to ERROR) are used to
post error messages with usrerr() and uferr(), respectively.
.PP
Example:
.sp
.nf
.ft CR
	xxhpp = hdralloc(nbands, sizeof(XXH_T *), fd, XXH_HNAME);
	xxhp = hdralloc(1, sizeof(XXH_T), fd, XXH_HNAME);
.ft R
.fi

.PP
\fBhdralloc\fP may be called by the header ingest functions (\fIxx\fPhread) to
allocate both individual headers and an array of header pointers.
.SH RETURN VALUE
.PP
generic pointer to newly allocated header; NULL if allocation failed.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.sp
.TP
can't allocate \fIname\fP header
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
