.TH "numdays" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBnumdays\fP - return number of days in a month
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

int
numdays(
	int		year,		|* year			*|
	int		month)		|* month (1 to 12)	*|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBnumdays\fP retuns the number of days in the given month of
the given year.
.SH RETURN VALUE
.PP
number of days in month
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
