.TH "wetbulb" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBwetbulb\fP - wet or ice bulb from air and dew point temperatures and air pressure
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "envphys.h"

double
wetbulb(
     double  ta,      /* air temperature (K) */
     double  dpt,     /* dewpoint temperature (K) */
     double  press)   /* total air pressure (Pa)  */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBwetbulb\fP routine wetbulb is called to compute wet or ice bulb temperature from values
of air and dewpoint temperatures (K), and air pressure (Pa),
using Richard Essery's equations for the psychrometric constant,
its value at specific temperatures from the Clausius-Clapeyron equation,
and solves for the Tw or Ti using the Newton-Raphson iterative approximation.
It returns wet or ice bulb temperture (K); works at all temperatures
(accounting for both fusion and vaporization).
.SH RETURN VALUE
.PP
Wet or Ice Bulb temperature (K)
.SH HISTORY
.TP
2012
written by D. Marks, USDA-ARS, NWRC;
