.TH "addsv" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBaddsv\fP - add a string to a strvec
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

STRVEC_T *
addsv(
	REG_1 STRVEC_T *p,
	char           *s)

.ft R
.fi
.SH DESCRIPTION
.PP
\fBaddsv\fP appends a copy of string s to strvec p.  If p is NULL, then a
new strvec is created with s as its first string.
.PP
\fBaddsv\fP is used by the IPW image header ingestion routines to maintain
multi-valued string parameters.
.SH RETURN VALUE
.PP
p, or a pointer to a new strvec if p is NULL, or NULL if any memory
allocations fail.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
