.TH "init_snow" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBinit_snow\fP - initialize the properties for the snowcover
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "snobal.h"

void
init_snow(void)

.ft R
.fi
.SH DESCRIPTION
.PP
This routine initializes the properties for the snowcover.  It
determines the number of layers, their individual properties,
the cold content for the snowcover and its layers, and the
snowcover's water content.  The following global variables
should be initialized before invoking this routine:
.sp
.nf
.ft CR
     z_s          depth of snowcover (m)
     rho          density of snowcover (kg/m^3)
     T_s          average temperature of snowcover (K)
     T_s_0        temperature of surface layer of snowcover (K)
     T_s_l        temperature of lower layer of snowcover (K)
     h2o_sat      % of liquid h2o saturation (0 to 1.0)

     max_h2o_vol  maximum liquid h2o content as volume ratio:
                         V_water/(V_snow - V_ice) (unitless)
.ft R
.fi
.SH RETURN VALUE
.PP
None.
.SH EXAMPLES
.SH GLOBALS READ
.sp
.nf
.ft CR
     h2o_sat
     layer_count
     m_s_0
     m_s_l
     max_h2o_vol
     rho
     T_s
     T_s_0
     T_s_l
     z_s
.ft R
.fi
.SH GLOBALS MODIFIED
.sp
.nf
.ft CR
     cc_s
     cc_s_0
     cc_s_l
     h2o
     h2o_max
     h2o_total
     h2o_vol
     m_s
     m_s_0
     m_s_l
     rho
     T_s
     T_s_0
     T_s_l
.ft R
.fi
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
