# Possible targets:
#- 
# distclean   Remove the files created during configuration.

.PHONY : help distclean

help :
	@sed -n 's/^#[- ]//p' Makefile

distclean :
	rm -f config.log config.status conf.h conf.ipw conf.mk host.h
