.TH "ndig" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBndig\fP - number of digits in an integer
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

int
ndig(
	int i)

.ft R
.fi
.SH DESCRIPTION
.PP
\fBndig\fP calculates the number of decimal digits needed to represent the
value of i, including the minus sign for negative values.
.SH RETURN VALUE
.PP
number of decimal digits in i
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
