.TH "access" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBaccess\fP - get pixel-access level of an image
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "image.h"

int
access(
     IMAGE_T *image)   /* image file descriptor */
.ft R
.fi
.SH DESCRIPTION
.PP
access returns the pixel-access level of an image.
.SH RETURN VALUE
.TP
PIXEL_ACCESS
Image's pixels are accessed as unsigned integers.
.sp
.TP
FPIXEL_ACCESS
Image's pixels are accessed as floating-point values.
