.TH "beta_0" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBbeta_0\fP - compute beta_0 for Henyey-Greenstein function
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "radiation.h"

double
betanaught(
     double  u0,     /* cosine of illumination angle   */
     double  g)      /* scattering asymmetry parameter */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBbeta_0\fP computes the value of beta_0 for a Henyey-Greenstein
scattering function, using a recursive relationship for the
Legendre coefficients.  beta_0 is the integral of the phase
function over the downward hemisphere.
.SH RETURN VALUE
.PP
beta_0 for Henyey-Greenstein scattering function
.SH DIAGNOSTICS
.PP
\fBbeta_0\fP Warns if the Legendre polynomial doesn't converge.
Values are printed to standard error to allow user to determine if this
is a problem.
.SH HISTORY
.TP
Jul 1989
Written by J. Dozier
