.TH "crhmake" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBcrhmake\fP - make an IPW CRH header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "crh.h"

CRH_T *
crhmake(
	int         nclass,	|* #classes     		 *|
	fpixel_t   *lo,		|* array of lower range values   *|
	fpixel_t   *hi,		|* array of higher range values  *|
	fpixel_t   *rep,	|* array of representative vals  *|
	pixel_t	    floor,	|* class floor value		 *|
	pixel_t	    ceil,	|* class ceiling value		 *|
	char       *annot,	|* annotation                    *|
	char       *units)	|* units of data                 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBcrhmake\fP allocates a single IPW CR header.  The header is initialized
with the arguments.
.SH RETURN VALUE
.PP
pointer to new CR header; NULL if error
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
