.TH "dew_pointp" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBdew_pointp\fP - dew point temperature with tolerance
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "envphys.h"

double
dew_pointp(
     double  e)      /* vapor pressure (Pa) */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBdew_pointp\fP returns the dew point temperature for a given vapor pressure with a tolerance threshold.
.SH RETURN VALUE
dew point temperature (K)
.SH HISTORY
.TP
Apr 1989
Fixed to accept saturation over ice.  D. Marks, USEPA, Corvallis, OR
.TP
Oct 2015
Accepts tolerance threshold.  S. Havens, USDA ARS, Boise, ID
