.TH "dt_diff" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBdt_diff\fP - compute difference between two date-times
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

void
dt_diff(
     datetime_t  *dt1,       /* first date-time                  */
     datetime_t  *dt2,       /* second date-time                 */

  /* output variables */

     int         *days,      /* # of days between dt1 and dt2    */
     int         *seconds)   /* # of seconds between dt1 and dt2 */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBdt_diff\fP determines the difference between two date-times.
It computes
the number of days and seconds from \fIdt2\fP to \fIdt1\fP.  If the second
date-time follows the first date-time, then the outputs will be negative.
.SH RETURN VALUE
.PP
None.
.SH HISTORY
.TP
Oct 1997
Written by J. Domingo, OSU.
