.TH "dupsv" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBdupsv\fP - duplicate a strvec
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

STRVEC_T *
dupsv(
	REG_1 STRVEC_T *p)

.ft R
.fi
.SH DESCRIPTION
.PP
\fBdupsv\fP duplicates the strvec pointed to by p.
.PP
\fBdupsv\fP is used by the IPW image header duplication routines to
duplicate strvec header values.
.SH RETURN VALUE
.PP
pointer to the duplicate strvec, or NULL if any memory allocations
fail.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
