.TH "evap" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBevap\fP - calculates evaporation rate
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "envphys.h"

double
evap(
     double  le,        /* latent heat transfer (W/m^2)  */
     double  ts)        /* surface temperature (K)       */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBevap\fP calculates the evaporation or condensation rate from
or onto a surface.
.SH RETURN VALUE
rate of water gain or loss (kg/sec/m^2) which is also the specific discharge in mm/sec
.SH HISTORY
.TP
Jul 1984
written by D. Marks, CSL (GSFC), UCSB;
.sp
.TP
Jun 1995
Converted from QIDPS to IPW by J. Domingo, OSU.
