.TH "fpclose" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBfpclose\fP - close floating-point I/O file descriptor
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "fpio.h"

int
fpclose(
	int fd)		|* file descriptor		*|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBfpclose\fP resets all floating-point I/O information associated with file
descriptor fd, then calls pxclose to close the associated file.
.PP
Call \fBfpclose\fP if you need to reclaim a file descriptor that has been
read|written by fpvread|fpvwrite.
.PP
Do not attempt any FP operations (including LQH access) to the file
descriptor after this function is called.
.SH RETURN VALUE
.PP
OK for success, ERROR for failure
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_fpiocb
.SH DIAGNOSTICS
.SH RESTRICTIONS
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
