.TH "fphdrs" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBfphdrs\fP - read, then write any floating-point headers
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "fpio.h"

void
fphdrs(
	int     fdi,		|* input image file descriptor	*|
	int	nbands,		|* # image bands		*|
	int     fdo)		|* output image file descriptor	*|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBfphdrs\fP copies all (remaining) image headers from filw descriptor fdi
to file descriptor fdo.  Any floating-point headers encountered that
are known to \fBfphdrs\fP (currently: LQ) are also ingested, and thus become
accessible to the fpio initialization routine.
.PP
Only the LQ header is recognized by this version of \fBfphdrs\fP.
.PP
\fBfphdrs\fP calls gethdrs; therefore, no further headers may be ingested
after \fBfphdrs\fP is called.  See gethdrs() for more info.
.PP
Call \fBfphdrs\fP if your program doesn't need to ingest any more headers,
but you want the floating-point headers read in order to initialize
the fpio package.
.SH RETURN VALUE
.PP
None.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
