.TH "fpvread" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBfpvread\fP - read floating-point vectors
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "fpio.h"

int
fpvread(
	int             fd,	  |* input file descriptor	 *|
	REG_2 fpixel_t *buf,	  |* -> floating-point buffer	 *|
	REG_5 int       npixv)	  |* # pixel vectors to read	 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBfpvread\fP reads npixv floating-point vectors from file descriptor fd
into buf.
.SH RETURN VALUE
.PP
number of floating-point vectors read; else ERROR for failure
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_fpiocb
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
