.TH "freesv" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBfreesv\fP - free an entire strvec
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

int
freesv(
	STRVEC_T *p)

.ft R
.fi
.SH DESCRIPTION
.PP
\fBfreesv\fP frees the entire strvec structure.
.SH RETURN VALUE
.PP
OK is the free was successful, ERROR otherwise.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
