.TH "geohmake" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBgeohmake\fP - make an IPW GEOH header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "geoh.h"

GEOH_T *
geohmake(
	double     bline,	|* begin line #			 *|
	double     bsamp,	|* begin sample #		 *|
	double     dline,	|* line increment		 *|
	double     dsamp,	|* sample increment		 *|
	char      *units,	|* units of measurement		 *|
	char      *csys)	|* coord system ID		 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBgeohmake\fP allocates a GEO header.  The header is initialized with the
remaining arguments.
.SH RETURN VALUE
.PP
pointer to new GEO header; NULL if error
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
