.TH "geohread" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBgeohread\fP - read an IPW GEOH header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "geoh.h"

GEOH_T **
geohread(
	int fd)

.ft R
.fi
.SH DESCRIPTION
.PP
\fBgeohread\fP reads a GEOH image header from file descriptor fd.  An array
of GEOH_T pointers is allocated, one per band.  If a band has a GEOH
header, then an GEOH_T header is allocated and its address is placed
in the corresponding array element; otherwise, the corresponding
array element is NULL.
.PP
Before calling \fBgeohread\fP, the caller must verify (by calling hrname())
that a GEOH header is available for ingesting.
.PP
\fBgeohread\fP is called by application programs to ingest GEOH headers.
.SH RETURN VALUE
.PP
pointer to array of GEOH_T pointers; else NULL if EOF or error
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.sp
.TP
can't allocate array of "geo" header pointers
"geo" header: bad band "\fIband\fP"
can't allocate "geo" header
"geo" header: key "\fIkey\fP" has no value
"geo" header: bad key "\fIkey\fP"
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
