.TH "geohspace" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBgeohspace\fP - get spacing from geodetic header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "geoh.h"

double
geohspace(
	GEOH_T *geoh)

.ft R
.fi
.SH DESCRIPTION
.PP
Geohspace returns grid spacing from geodetic header.
.SH RETURN VALUE
.PP
grid spacing	(if errno = 0)
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
