.TH "get_proj_units" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBget_proj_units\fP - get name for projection units ID
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "mapproj.h"

char *
get_proj_units(
	int	units_id)	|* projection units ID		 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBget_proj_units\fP returns the name of the geographic projection units
that corresponds to the given units ID.  If an invalid ID is
specified, the name "(unknown)" is returned.
.SH RETURN VALUE
.PP
pointer to name of projection units
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
The returned character string is in static memory; so do NOT
attempt to "free" it up.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
