.TH "has_lqh" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBhas_lqh\fP - does an image's band have an LQ header?
.SH SYNOPSIS
.SH DESCRIPTION
.SH RETURN VALUE
.PP
None.
.SH EXAMPLES
.SH GLOBALS READ
.PP
None.
.SH GLOBALS MODIFIED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
