.TH "hnbits" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBhnbits\fP - number of bits in image band
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "bih.h"

int
hnbits(
	int             fd,	|* image file descriptor	 *|
	int             band)	|* image band #			 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBhnbits\fP determines the number of bits per band in the specified band
of the image currently being read/written on file descriptor fd.
.PP
\fBhnbits\fP may not be called before a BIH is read/written from/to fd.
.SH RETURN VALUE
.PP
number of bits per band
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_bih
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
