.TH "hwprmb" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBhwprmb\fP - write preamble record
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "hdrio.h"

int
hwprmb(
	int             fd,	   |* output file descriptor	 *|
	const char     *name,	   |* header name		 *|
	int             band,	   |* header band number	 *|
	const char     *version)   |* header version string	 *|

.ft R
.fi
.SH DESCRIPTION
.PP
Hwid constructs a header ID from header name "name", header band
number "band", and header version string "version", and writes the
corresponding preamble record to "fd".
.SH RETURN VALUE
.PP
OK for success, ERROR for failure
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
All values placed in the preamble record will be truncated to fit the
destination field width.  See hdrio.h for the specifics.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
