.TH "lqhmake" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBlqhmake\fP - make an IPW LQH header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "lqh.h"

LQH_T *
lqhmake(
	int             nbits,	  |* #bits / pixel		 *|
	int             nbkpts,	  |* #breakpoints		 *|
	pixel_t        *ival,	  |* array of integer bkpts	 *|
	fpixel_t       *fval,	  |* array of floating-pt bkpts	 *|
	char           *units,	  |* fpixel units of measurement *|
	char           *interp)	  |* interpolation function name *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBlqhmake\fP allocates a single IPW LQ header.  The header is initialized
with the arguments.
.SH RETURN VALUE
.PP
pointer to new LQ header; NULL if error
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
