.TH "lqhread" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBlqhread\fP - read an IPW LQH header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "lqh.h"

LQH_T **
lqhread(
	int        fd)		|* image file descriptor	 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBlqhread\fP reads a LQH image header from file descriptor fd.  An array
of LQH_T pointers is allocated, one per band.  If a band has a LQH
header, then an LQH_T header is allocated and its address is placed
in the corresponding array element; otherwise, the corresponding
array element is NULL.
.PP
Before calling \fBlqhread\fP, the caller must verify (by calling hrname())
that a LQH header is available for ingesting.
.SH RETURN VALUE
.PP
pointer to array of LQH_T pointers; else NULL if EOF or error
.SH EXAMPLES
.SH GLOBALS ACCESSED
.SH DIAGNOSTICS
.sp
.TP
can't allocate array of "lq" header pointers
"lq" header: bad band "\fIband\fP"
can't allocate "lq" header
"lq" header: key "\fIkey\fP" has no value
"lq" header: bad key "\fIkey\fP"
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
