.TH "msolve" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBmsolve\fP - solve a linear system using matrices
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

void
msolve(
     double  **A,   /* n-by-n matrix of coefficients    */
     double   *x,   /* output: answers for n variables  */
     double   *b,   /* n-by-1 matrix of constant values */
     long      n)   /* # of linear equations            */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBmsolve\fP solves a set of linear equations using matrices.  The
set contains \fIn\fP linear equations for \fIn\fP variables.  The set
represents the linear system \fIAx\fP = \fIb\fP.  This function solves this
system by Gaussian elimination and then back-substitution.
.SH RETURN VALUE
.PP
None.
.SH HISTORY
.TP
Jan 1992
Written by Dana Jacobsen, EPA ERL-C
