.TH "mwgamma" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBmwgamma\fP - gamma values for twostream calculations
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "radiation.h"

void
mwgamma(
     double   u0,       /* cosine of illumination angle     */
     double   w,        /* single-scattering albedo         */
     double   g,        /* scattering asymmetry parameter   */
     double  *gam,      /* output gamma values (4)          */
     int      method)   /* DELTA_EDDINGTON or MEADOR_WEAVER */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBmwgamma\fP computes the gamma values for twostream calculations.
The method used to compute the gamma values is specified by one of two
constants defined in the "radiation.h" header file:
DELTA_EDDINGTON or MEADOR_WEAVER.
.PP
.SH RETURN VALUE
.PP
None.
.SH HISTORY
.TP
Jun 1989
Written by J. Dozier
.SH SEE ALSO
.TP
IPW:
twostream()
.PP
Meador 1980
.br
