.TH "orhmake" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBorhmake\fP - make an IPW ORH header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "orh.h"

ORH_T *
orhmake(
	char   *orient,		|* orientation			 *|
	char   *origin)		|* corner of origin		 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBorhmake\fP allocates an OR header.  The header is initialized with the
remaining arguments.
.SH RETURN VALUE
.PP
pointer to new OR header; NULL if error
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
