.TH "psychrom" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBpsychrom\fP - solve psycrometric equation
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "envphys.h"

double
psychrom(
     double  tdry,    /* dry bulb temperature (K) */
     double  twet,    /* wet bulb temperature (K) */
     double  press)   /* total air pressure (Pa)  */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBpsychrom\fP solves the psycrometric equation using wet/dry bulb
temperatures, and air pressure data.  It
calculates vapor pressure as function of wet & dry bulb temps;
works at all temperatures (accounts for both fusion and vaporization).
.SH RETURN VALUE
.PP
vapor pressure	(Pa)
.SH HISTORY
.TP
1983
written by J. Dozier, CSL;
.sp
.TP
1986
modified by D. Marks, CSL;
.sp
.TP
May 1995
Converted from QDIPS to IPW by J. Domingo, OSU.
