.TH "pvread" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBpvread\fP - read pixel vectors
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "pixio.h"

int
pvread(
	int             fd,	  |* input file descriptor	 *|
	REG_4 pixel_t  *buf,	  |* -> pixel buffer		 *|
	int             npixv)	  |* # pixel vectors to read	 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBpvread\fP reads npixv pixel vectors from file descriptor fd into buf.
.PP
\fBpvread\fP is the lowest level of IPW input that represents pixel values
in a single format (unsigned integers).
.SH RETURN VALUE
.PP
number of pixel vectors read; else ERROR for failure
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_piocb
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
