.TH "pvwrite" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBpvwrite\fP - write pixel vectors
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "pixio.h"

int
pvwrite(
	int             fd,	  |* input file descriptor	 *|
	pixel_t        *buf,	  |* -> pixel buffer		 *|
	int             npixv)	  |* # pixel vectors to write	 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBpvwrite\fP writes npixv pixel vectors from buf into file descriptor fd.
.PP
\fBpvwrite\fP is the lowest level of IPW output that represents pixel values
in a single format (unsigned integers).
.SH RETURN VALUE
.PP
number of pixel vectors written; else ERROR for failure
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_piocb
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
