.TH "read_proj" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBread_proj\fP - read projection definition file
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "mapproj.h"

struct projdef *
read_proj(
	char	*filename)	|* name of projection def file	 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBread_proj\fP reads the given projection definition file, writes the
contents into a projdef struct, and returns a pointer to the
struct.  The projection definition files are ASCII files with the
following format:
.sp
.nf
.ft CR
	projection ID
	units code
	zone code
	datum code
	projection parameters (15 values)
.ft R
.fi
.SH RETURN VALUE
.PP
non-NULL	pointer to allocated & initialized projdef struct
.PP
NULL		error occurred; message stored via 'usrerr'
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
