.TH "ri_no" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBri_no\fP - bulk Richardson number at geometric mean height
.SH SYNOPSIS
.sp
.nf
.ft CR
#include	"ipw.h"
#include	"envphys.h"

double
ri_no(
     double  z2,   /* upper height (m)                          */
     double  z1,   /* lower height (m) (maybe roughness length) */
     double  t2,   /* virtual temperature at z2 (K)             */
     double  t1,   /*    "        "       "  z1  "              */
     double  u2,   /* wind speed at z2 (m/s)                    */
     double  u1)   /*  "     "   "  z1   "   (may be zero)      */
.ft R
.fi
.SH DESCRIPTION
.PP
ri_no calculates the bulk Richardson number at the geometric
mean height between two given heights.
.SH RETURN VALUE
bulk Richardson number
.SH HISTORY
.TP
Jun 1995
Converted from QDIPS (originally named "Ri_no") to IPW by J. Domingo, OSU.
