.TH "rmlead" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBrmlead\fP - skip leading white space in string
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

char *
rmlead(
	char *s)

.ft R
.fi
.SH DESCRIPTION
.PP
\fBrmlead\fP skips leading white-space characters (space, tab,
carriage-return, newline, formfeed) in s.
.PP
s must be EOS-terminated.
.SH RETURN VALUE
.PP
pointer to the first non-white-space character in s
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
