.TH "sathwrite" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBsathwrite\fP - write an IPW SATH header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "sath.h"

int
sathwrite(
	int        fd,		|* output file descriptor	 *|
	SATH_T   **sathpp)	|* -> array of SATH pointers	 *|

.ft R
.fi
.SH DESCRIPTION
.sp
.nf
.ft CR
     sathwrite writes the array of SATH headers pointed to by sathpp
.ft R
.fi
.PP
to file descriptor fd.
.SH RETURN VALUE
.PP
OK for success, ERROR for failure
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
