.TH "set_geoh" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBset_geoh\fP - set GEO header for an image's band
.SH SYNOPSIS
.SH DESCRIPTION
.SH RETURN VALUE
.PP
None.
.SH EXAMPLES
.SH GLOBALS READ
.PP
None.
.SH GLOBALS MODIFIED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
