.TH "sunhwrite" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBsunhwrite\fP - write an IPW SUNH header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "file.h"

int sunhwrite(fd, sunhpp)
int fd;
SUNH_T **sunhpp;

.ft R
.fi
.SH DESCRIPTION
.PP
Sunhwrite writes the array of SUNH headers pointed to by sunhpp
to file descriptor fd.
.SH RETURN VALUE
.PP
OK for success, ERROR for failure
.SH EXAMPLES
.SH GLOBALS ACCESSED
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
Sunhwrite writes the values in float precision, even though
internally they are stored in double precision.
.SH HISTORY
.TP
May 1993
	Changed ftoa calls to dtoa.  Limited precision was causing
problems.
.SH BUGS
.SH SEE ALSO
