.TH "sunrise" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBsunrise\fP - sunrise time (GMT) for a given place and date
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "solar.h"

datetime_t *
sunrise(
     double  lat,     /* latitude (radians)  */
     double  lon,     /* longitude (radians) */
     int     year,    /* year (e.g., 1997)   */
     int     month,   /* month (1 - 12)      */
     int     day)     /* day (1 - 31)        */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBsunrise\fP determines the time of sunrise at a given location
(specified by its latitude and longitude) and date.  South
latitudes and west longitudes are negative.
.PP
The returned date-time structure contains the GMT time of local
sunrise.  Note: it does not account for local horizons.
.SH RETURN VALUE
.TP
non-NULL
GMT time of sunrise.
.sp
.TP
NULL
Error occurred, and an explantory message stored via
the "usrerr" routine.
.SH HISTORY
.TP
Oct 1997
Extracted function from the program \fBsunlight\fP.  J. Domingo, OSU
