.TH "twostream" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBtwostream\fP - twostream solution for horizontal surface
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "radiation.h"

int
twostream(
     double  *gamma,   /* vector of gamma coefficients    */
     double   omega,   /* single-scattering albedo        */
     double   mu0,     /* cosine of incidence angle       */
     double   tau,     /* optical depth of layer          */
     double   r0,      /* reflectance of substrate        */

  /* output variables */

     double  *refl,    /* reflectance of layer            */
     double  *trans,   /* total transmittance of layer
                            (compensated for mu0)         */
     double  *btrans)  /* direct transmittance of layer
                            (compensated for mu0)         */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBtwostream\fP provides the twostream solution for a single-layer
atmosphere over a horizontal surface, using the solution method in
Meador 1980.
.SH RETURN VALUE
.PP
OK for success
.PP
ERROR for failure
.PP
1 if the layer is semi-infinite
.SH HISTORY
.TP
Oct 1988
Written by J. Dozier
.SH SEE ALSO
.TP
IPW:
mwgamma()
.PP
Meador 1980
.br
