.TH "uclose" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBuclose\fP - close IPW file descriptor
.SH SYNOPSIS
.sp
.nf
.ft CR
int
uclose(
	int             fd)	    |* file descriptor		 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBuclose\fP closes an IPW file descriptor and clears the associated UIO
control block.  If the descriptor refers to an output file, any
pending buffered output is first flushed.
.SH RETURN VALUE
.PP
OK	The file was closed succesfully.
.PP
ERROR	An error occurred.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_uiocb[fd]	UIO control block for file descriptor fd
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
