.TH "ueof" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBueof\fP - check for UIO end-of-file
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

bool_t
ueof(
	int             fd)	|* file descriptor		 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBueof\fP tests whether there any any data remaining to be read from file
descriptor fd, which must have been opened for reading by uropen.
.PP
\fBueof\fP is typically called after an application program has finished
reading an image, to ensure that the header correctly represented the
size of the image.
.SH RETURN VALUE
.PP
TRUE	End-of-file has been reached
.PP
FALSE	End-of-file has not been reached
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_uiocb
.SH DIAGNOSTICS
.SH RESTRICTIONS
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
