.TH "units_as_str" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBunits_as_str\fP - convert units id into a string
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "units.h"

char *
units_as_str(
	UNITS_T           id)	|* units id 			*|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBunits_as_str\fP converts a units \fIid\fP into a string (usually for
printing).
.SH RETURN VALUE
.PP
\fBunits_as_str\fP returns a string corresponding to the given units id.
If the units id is not valid, the string "unknown" is returned.
.PP
The pointer returned by this function points to static memory;
therefore, do not try free up (i.e., deallocate) this string.
.SH EXAMPLES
.PP
This function call
.sp
.nf
.ft CR
	printf ("Error: Expected the units to be %s.",
		units_as_str(U_METERS_PER_SECOND));
.ft R
.fi

.PP
produces this output:
.sp
.nf
.ft CR
	Error: Expected the units to be m/s.
.ft R
.fi
.SH GLOBALS ACCESSED
.PP
_unitStrings
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.TP
Nov 1995
	Written by J. Domingo, OSU
.SH BUGS
.PP
None.
.SH SEE ALSO
