.TH "uropen" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBuropen\fP - open UNIX file for reading
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

int
uropen(
	const char      *name)	|* file name			 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBuropen\fP opens the file name for reading.  The name "-" is understood to
mean the standard input.
.PP
Use \fBuropen\fP wherever you would normally use the UNIX system call open()
to open a file for reading.
.SH RETURN VALUE
.PP
>= 0	A readable UNIX file descriptor for successful open.
.PP
ERROR	An error occurred.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
