.TH "usage" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBusage\fP - print usage message and exit
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "getargs.h"

void
usage(void)

.ft R
.fi
.SH DESCRIPTION
.PP
\fBusage\fP prints a \fBusage\fP message on the standard error output, then exits
with a nonzero status.  The \fBusage\fP message contains the command name, a
one line description of the command, and a synopsis of the command's
options.
.SH RETURN VALUE
.PP
This function does not return; it terminates the program by calling
the ipwexit function.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_argv
_descrip
_optv
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
