.TH "ustdout" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBustdout\fP - initialize UIO on standard output
.SH SYNOPSIS
.sp
.nf
.ft CR
int
ustdout(void)

.ft R
.fi
.SH DESCRIPTION
.PP
\fBustdout\fP initializes the UIO package for writing the program's standard
output.
.PP
\fBustdout\fP should be called by an IPW main() if the program will be
writing image data to the standard output.  \fBustdout\fP should NOT be
called if the program uses UNIX stdio output functions (e.g.,
printf).
.PP
\fBustdout\fP causes program termination if any errors are encountered.
.SH RETURN VALUE
.PP
writable UNIX file descriptor
.SH EXAMPLES
.SH GLOBALS ACCESSED
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
