.TH "uwflush" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBuwflush\fP - flush buffered UIO output
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

int
uwflush(
	int     fd)		|* file descriptor		 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBuwflush\fP forces any pending UIO output to be written to file
descriptor fd.
.PP
\fBuwflush\fP is usually called to force pending output down a pipe before
beginning a potentially lengthy calculation.
.SH RETURN VALUE
.PP
OK	for success
.PP
ERROR	for failure
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_uiocb
.SH DIAGNOSTICS
.SH RESTRICTIONS
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
