.TH "uwrite" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBuwrite\fP - UNIX write
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

int
uwrite(
	int             fd,	   |* output file descriptor	 *|
	const addr_t    buf,	   |* buffer to write from	 *|
	int             nbytes)	   |* number of bytes to write	 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBuwrite\fP is a reliable interface to the UNIX write function.  The
various types of write errors are detected and folded into a single
error return.
.PP
It is considered an error for UNIX write to return any number other
than the number of bytes that were requested to be written.
.PP
Use \fBuwrite\fP wherever you would normally use the UNIX system call
write.
.SH RETURN VALUE
.PP
>= 0	number of bytes written
.PP
ERROR	for failure
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_uiocb
.SH DIAGNOSTICS
.sp
.TP
"incomplete write"
.br
	some number of bytes less than the number requested were
	written.  This is not necessarily due to a hard I/O error.
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.SH SEE ALSO
