.TH "waterday" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBwaterday\fP - returns day of water year for a given date
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

int
waterday(
	int 	year,		|* e.g., 1997			*|
	int 	month,		|* [1 - 12]			*|
	int 	day)		|* [1 - 31]			*|
	int    *wateryear)	|* output [ year or year + 1 ]	*|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBwaterday\fP returns the day of the water year for the given date.
The "water year" runs from October 1 to September 30.  Water years
are designated by the year they *end* in.  For example, the 1997
water year runs from Oct 1, 1996 to September 30, 1997.
The output parameter 'wateryear' is assigned the water year for
the given date.
.SH RETURN VALUE
.PP
1 - 366
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
