.TH "winhwrite" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBwinhwrite\fP - write an IPW WINH header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "file.h"

int
winhwrite(
	int             fd,	|* output file descriptor	 *|
	WINH_T        **winhpp)	|* -> array of WINH pointers	 *|

.ft R
.fi
.SH DESCRIPTION
.sp
.nf
.ft CR
     winhwrite writes the array of WINH headers pointed to by winhpp
.ft R
.fi
.PP
to file descriptor fd.
.SH RETURN VALUE
.PP
OK for success, ERROR for failure
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.TP
May 1993
	Changed ftoa calls to dtoa.  All headers now write double
precision which should clean up some problems.  Dana Jacobsen.
.SH BUGS
.PP
None.
.SH SEE ALSO
