.TH "winhfree" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBwinhfree\fP - free all left over parts of a WIN header
.SH SYNOPSIS
.sp
.nf
.ft CR
     #include "winh.h"

int
winhfree(
	WINH_T **  winhpp,
	int        nbands)

.ft R
.fi
.SH DESCRIPTION
.PP
\fBwinhfree\fP frees an entire winhpp structure.
.SH RETURN VALUE
.sp
.nf
.ft CR
     OK for success, ERROR for failure
.ft R
.fi
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
