.TH "winhdup" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBwinhdup\fP - duplicate an IPW WINH header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "winh.h"

WINH_T **
winhdup(
	WINH_T        **oldhpp,	   |* -> old WINH array		 *|
	int             nbands)	   |* # header bands		 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBwinhdup\fP creates a duplicate of the IPW WINH header pointed to by
"old".
.PP
\fBwinhdup\fP is an easy way for applications programs to create a new WINH
(e.g., for an output image, after having read the WINH for an input
image).
.SH RETURN VALUE
.PP
A pointer to the duplicate header is returned.  NULL is returned if
an error occurs.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
