.TH "zone2str" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBzone2str\fP - convert time zone (in minutes) to string
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

char *
	int zone,	/* minutes west of Greenwich */
	int isdst)	/* is Daylight Savings Time? */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBzone2str\fP returns the short time zone name given an offset from GMT
(now known as UTC) time and a flag as to whether Daylight Savings
time is in effect.  DST can affect the string returned.
.PP
Since a single longitude can run through multiple countries, the
string returned is not correct for all countries.  Many times do
not have timezone's associated with them, so are returned as a
string of the form "GMT+0:00" where "+0:00" is the offset given.
.SH RETURN VALUE
.PP
A static string represtening the timezone name.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.TP
May 1993
	Written by Dana Jacobsen, ERL-C.
.SH BUGS
.PP
None.
.SH SEE ALSO
.TP
UNIX
	timezone
