.TH "ucopy" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBucopy\fP - copy between open files
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

*	long
*	ucopy(
*		int	      fdi,	|* input file descriptor	 *|
*		int           fdo,	|* output file descriptor	 *|
*		REG_3 long    ncopy)	|* # bytes to [try to] copy	 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBucopy\fP copies ncopy bytes from file descriptor fdi to file descriptor
fdo.
.PP
Use \fBucopy\fP to transfer data unconditionally between open files.
.SH RETURN VALUE
.PP
>= 0	number of bytes copied
.PP
ERROR	an error occurred.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
