NAME := ipw
DESCRIPTION := Main IPW library

DIRS := main error math strvec datetime util uio pixio fpio units \
	hdrio bih lqh geoh winh horh orh skewh sath sunh crh gethdrs \
	mapproj

CONF_INCLUDE_FILES := conf.h host.h site.h

INCLUDE_FILES := ipw.h _datetime.h _error.h _main.h _math.h _sort.h \
	_str.h _types.h _uio.h _util.h $(CONF_INCLUDE_FILES)

include $(IPW)/make/library
