.TH "lqh" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBlqh\fP - get LQ header associated with file descriptor
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "lqh.h"

LQH_T **
lqh(
	int		fd)	|* image file descriptor	*|

.ft R
.fi
.SH DESCRIPTION
.PP
pointer to the LQ header array associated with file descriptor fd; or
NULL if there are no LQ headers associated with file descriptor fd.
.SH RETURN VALUE
.PP
pointer to the LQ header array associated with file descriptor fd; or
NULL if there are no LQ headers associated with file descriptor fd.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_lqh
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
