.TH "usrerr" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBusrerr\fP - log user's error message string
.SH SYNOPSIS
.sp
.nf
.ft CR
void usrerr(const char *format, ...)

.ft R
.fi
.SH DESCRIPTION
.PP
Usrerr saves the error message described by the printf-style "format"
and "args" in a place accessible to the _error() error handler.
.SH RETURN VALUE
.PP
None.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_usrerr
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
