.TH "skiphdrs" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBskiphdrs\fP - skip IPW image headers
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "gethdrs.h"

void
skiphdrs(
	int      fd)		|* input image file descriptor	 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBskiphdrs\fP skips (i.e. reads and discards) all IPW image headers on
file descriptor fd.
.PP
\fBskiphdrs\fP is a simple way to skip all remaining headers on an input
image, once any desired headers have been ingested.
.SH RETURN VALUE
.PP
None.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.sp
.TP
can't skip \fIheader-name\fP header
header read error
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
