.TH "itoa" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBitoa\fP - convert integer to string
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

char *
itoa(
	char    *s,		|* -> output string		 *|
	int      i)		|* input integer		 *|

.ft R
.fi
.SH DESCRIPTION
.PP
Itoa stores the ASCII representation of "i", followed by an EOS, into
the character array pointed to by "s".
.PP
The array pointed to by "s" must be large enough to hold the ASCII
representation of "i", plus a trailing EOS.
.SH RETURN VALUE
.PP
Itoa returns the value of the pointer "s".
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
