CATEGORY := math
DESCRIPTION := mathematical functions

FUNCS := akcoef apfit dtoa hbit ipow2 itoa ltoi msolve ndig rotate seval \
	 splint zerobr

PRIVATE_SRCS := mvalloc.c

include $(IPW)/make/funcCategory
