.TH "orhfree" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBorhfree\fP - free all left over parts of a OR header
.SH SYNOPSIS
.sp
.nf
.ft CR
     #include "orh.h"

     int
orhfree(
	ORH_T **orhpp,
	int     nbands)

.ft R
.fi
.SH DESCRIPTION
.PP
\fBorhfree\fP frees an entire orhpp structure.
.SH RETURN VALUE
.sp
.nf
.ft CR
     OK for success, ERROR for failure
.ft R
.fi
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
