.TH "crhread" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBcrhread\fP - read an IPW CRH header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "crh.h"

CRH_T **
crhread(
	int             fd)	|* image file descriptor	 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBcrhread\fP reads a CRH image header from file descriptor fd.  An array
of CRH_T pointers is allocated, one per band.  If a band has a CRH
header, then an CRH_T header is allocated and its address is placed
in the corresponding array element; otherwise, the corresponding
array element is NULL.
.PP
Before calling \fBcrhread\fP, the caller must verify (by calling hrname())
that a CRH header is available for ingesting.
.SH RETURN VALUE
.PP
pointer to array of CRH_T pointers; else NULL if EOF or error
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_crh
.SH DIAGNOSTICS
.sp
.TP
can't allocate array of "cr" header pointers
"cr" header: bad band "\fIband\fP"
can't allocate "cr" header
"cr" header: key "\fIkey\fP" has no value
"cr" header: bad key "\fIkey\fP"
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
