CATEGORY := sunh
DESCRIPTION := sun geometry headers

FUNCS := sunhmake sunhread sunhwrite

PRIVATE_SRCS := _sunhcheck.c

INCLUDE_FILES := sunh.h

include $(IPW)/make/funcCategory

_sunhcheck.o sunhread.o sunhwrite.o : _sunh.h
