CATEGORY := skewh
DESCRIPTION := image skew headers

FUNCS := skewhmake skewhread skewhwrite

PRIVATE_SRCS := _skewhcheck.c

INCLUDE_FILES := skewh.h

include $(IPW)/make/funcCategory

_skewhcheck.o skewhread.o skewhwrite.o : _skewh.h
