.TH "orhdup" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBorhdup\fP - duplicate an IPW ORH header
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "orh.h"

ORH_T **
orhdup(
	ORH_T         **oldhpp,	|* -> old ORH array		 *|
	int             nbands)	|* # header bands		 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBorhdup\fP creates a duplicate of the IPW ORH header pointed to by
"old".
.PP
\fBorhdup\fP is an easy way for applications programs to create a new ORH
(e.g., for an output image, after having read the ORH for an input
image).
.SH RETURN VALUE
.PP
A pointer to the duplicate header is returned.  NULL is returned if
an error occurs.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
