.TH "sati" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBsati\fP - saturation vapor pressure over ice
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "envphys.h"

double
sati(
        double  tk)             /* air temperature (K)  */
.ft R
.fi
.SH DESCRIPTION
.PP
sati returns the saturation vapor pressure over ice (in Pa)
as a function of air temperature.
.SH RETURN VALUE
.PP
saturation vapor pressure (Pa).
.SH HISTORY
.TP
Jul 1982
 written by J. Dozier, Department of Geography, UCSB
