.TH "hrband" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBhrband\fP - get current header band number
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "hdrio.h"

int
hrband(
	int      fd)		|* input file descriptor	 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBhrband\fP returns the band number of the image header currently being
read from file descriptor fd, or NO_BAND if the header applies to all
bands in the image.
.PP
Call \fBhrband\fP after you call hrname, to see which band (if any) the
header belongs to.
.SH RETURN VALUE
.PP
Current image header band number, or NO_BAND.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_hdriocb[fd]
.SH DIAGNOSTICS
.SH RESTRICTIONS
.SH HISTORY
.SH BUGS
.PP
The NO_BAND value is necessarily negative, since any positive integer
is a valid band number.  It is therefore easy to mistake NO_BAND for
an error return.
.PP
Hrband returns NO_BAND even if there is no current image header
.SH SEE ALSO
