.TH "not_a_tty" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBnot_a_tty\fP - make sure that an image file is not a terminal
.SH SYNOPSIS
.SH DESCRIPTION
.SH RETURN VALUE
.PP
None.
.SH EXAMPLES
.SH GLOBALS READ
.PP
None.
.SH GLOBALS MODIFIED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
