CATEGORY := datetime
DESCRIPTION := dates and times

FUNCS := add_to_dt dt2fmtstr dt2str dt_diff dt_in_order gmt2local leapyear \
	 local2gmt make_dt now_dt numdays sec2hms str2dt waterday wday2mday \
	 weekday yday2mday yearday zone2str

PRIVATE_SRCS := 

include $(IPW)/make/funcCategory
