.TH "g_soil" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBg_soil\fP - conduction heat flow between snow and soil
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "snow.h"

double
g_soil(
     double  rho,    /* snow layer's density (kg/m^3)             */
     double  tsno,   /* snow layer's temperature (K)              */
     double  tg,     /* soil temperature (K)                      */
     double  ds,     /* snow layer's thickness (m)                */
     double  dg,     /* depth of soil temperature measurement (m) */
     double  pa)     /* air pressure (Pa)                         */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBg_soil\fP calculates the heat flow between a snow layer and the
soil accounting for both conduction and vapor transport.  See pages
45 - 47 in the reference below.
Assumes soil texture to be as in a moist sandy soil, based on
heat flux data from RMSP (A. Winstral & D. Marks, NWRC, 2003)
.SH RETURN VALUE
.PP
heat transfer between soil and snow (J/m^2)
.SH HISTORY
.TP
Aug 1984
written by D. Marks, CSL (GSFC), UCSB;
.sp
.TP
May 1995
Converted from QDIPS to IPW by J. Domingo, OSU
.TP
Sep 2003
Modified to use conductivity for a
moist sandy soil, by D. Marks, NWRC.
.SH SEE ALSO
.PP
Anderson 1976
.br
