CATEGORY := solar
DESCRIPTION := solar geometry and radiation

FUNCS := ephemeris sunpath sunangle sunrise sunset

PRIVATE_SRCS := _sunpos.c

INCLUDE_FILES := solar.h

include $(IPW)/make/funcCategory
