.TH "new_tsno" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBnew_tsno\fP - calculates snow layer's new temperature
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "snow.h"

double
new_tsno(
     double  spm,    /* layer's specific mass (kg/m^2)        */
     double  t0,     /* layer's last temperature (K)          */
     double  ccon)   /* layer's adjusted cold content (J/m^2) */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBnew_tsno\fP calculates a new temperature for a snow layer from its
adjusted cold content, and the layer's last (previous) temperature.
.PP
The layer's specific mass (the argument \fIspm\fP) can be computed by
multiplying the layer's thickness (m) by its density (kg/m^3).
.SH RETURN VALUE
.PP
snow layer's new temperature (K)
.SH HISTORY
.TP
Aug 1984
written by D. Marks, CSL (GSFC), UCSB;
.sp
.TP
May 1995
Converted from QDIPS to IPW by J. Domingo, OSU
