.TH "classify" "1" "10 April 1998" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBclassify\fP - separate pixels into classes using ranges of values
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBclassify\fP [ \fB-i\fP \fIclass_file\fP ] [ \fB-h\fP \fIcrh\fP ] [ \fB-m\fP \fImask\fP ]
      [ \fB-f\fP \fIfloor\fP ] [ \fB-c\fP \fIceil\fP ] [\fIimage\fP]
.ft R
.fi
.SH DESCRIPTION
.PP
\fBclassify\fP reads an IPW image and creates an image whose pixel values
contain class identifiers for the corresponding input image pixel.
The classes are defined by the given input file containing lo,hi
and representative values for each class or by the given class range
header.
.SH OPTIONS
.TP
\fB-i\fP \fIclass_file\fP
input file containing lo, hi and representative values (floating
point) for each class; must be sorted in increasing data values,
seperated by "white space" (blanks or tabs, not commas);
.sp
Note 1: the number of classes is specified in the class range
file, and that will be reported in the crh; it will, however,
be mapped as nclasses + 1, to include a NO_DATA class.
.sp
Note 2: classes defined in the class range file must be
continuous, such that there are no unclassified gaps in the
ranges;
.sp
Note 3: the class representative value must be => "lo",
and < "hi"; "hi" is considered either part of the next class,
or beyond the range of the data;
.sp
.TP
\fB-h\fP \fIcrh\fP
input class range header (incompatible with \fB-i option;
at least one of \fB-i, \fB-h must be specified)
.sp
.TP
\fB-m\fP \fImask\fP
mask image - for all 0 pixels in mask image, set corresponding
classified pixel to NO_DATA (class 0)
.sp
.TP
\fB-f\fP \fIfloor\fP
class value for data values < lo (defaults to NO_DATA)
(ignored if \fB-h option specified)
.sp
.TP
\fB-c\fP \fIceil\fP
class value for data values > hi (defaults to NO_DATA)
(ignored if \fB-h option specified)
.SH OPERANDS
.TP
[\fIimage\fP]
	image	input image (defaults to stdin)
.sp
.SH EXAMPLES
.PP
To convert a dem to a classified image with two specified elevation
classes, with everyting below set to 0 (NO_DATA), and everything above
set to class 2:
1) the class range file "cf" looks like this:
.sp
.nf
.ft CR
	1500 3000 2000
	3000 5000 3500
.ft R
.fi

.PP
and 2) the command is:
.sp
.nf
.ft CR
	classify -i cf -c 2 dem >dem.class
.ft R
.fi
.SH FILES
.sp
.nf
.ft CR
     either a class range definition file, or a class range header must be
     supplied
.ft R
.fi
.SH DIAGNOSTICS
.PP
None
.SH RESTRICTIONS
.PP
either the \fB-i or \fB-h option may be supplied, but not both
requirements for the class range file (\fB-i option) are very restrictive
.SH HISTORY
.TP
May 1990
  Written by Kelly Longley, Oregon State University,
Environmental Research Laboratory, Corvallis OR
.TP
Aug 1997
  Converted to IPW Version 2.0, D. Marks, USGS, ERL-C
.SH BUGS
.PP
The requirements for the class range file are cumbersome and restrictive;
It would be nice to relax this to allow discontinuous classes,
and assignment of any desired representative value.
.SH SEE ALSO
.TP
IPW
	\fBclasseq\fP,
\fBclmask\fP,
\fBdeclass\fP,
\fBmkcrh\fP
