.TH "cloud" "1" "5 March 2015" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBcloud\fP - estimate cloudcover from tmax, tmin
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBcloud\fP [\fIimage\fP]
.ft R
.fi
.SH DESCRIPTION
.PP
\fBcloud\fP reads Tmax, Tmin1, Tmin2, and deltaT_average where:
.sp
.nf
.ft CR
	Tmax		current days max air temp (C)
	Tmin1		current days min air temp (C)
	Tmin2		next days min air temp (C)
	deltaT_average	average dirunal temperature range
			(weekly or monthly) (C)
.ft R
.fi

.PP
(default: standard input), and writes cloudiness coeficient (0.0-1.0)
to the standard output.
The daily diurnal temperature range (deltaT) is calculated from the
daily maximum temperature (Tmax) and the average of today's minimum
temperature and tomorrow's minimum temperature (Tmin2).
.PP
deltaT is compared to the weekly or monthly average diurnal temperature
range (deltaT_average), using the formula of Bristow and Campbell (1984):
The output image is calculated as Bristow and Campbell (1984):
.sp
.nf
.ft CR
	cloud_coef = 1 - exp(-B deltaT ^ C)
.ft R
.fi

.PP
where:
.sp
.nf
.ft CR
	B = 0.036 exp (-0.154 deltaT_average)
	C = 2.4 (constant)
.ft R
.fi
.SH OPTIONS
.PP
None
.SH OPERANDS
.PP
None
.SH EXAMPLES
.PP
To calculate cloudiness for the following air temperature data:
.PP

.sp
.nf
.ft CR

	cloud

	Input Tmax, Tmin1, Tmin2, deltaT_ave;
	24 5 7 20

	0.18 (output)
.ft R
.fi
.SH FILES
.sp
.nf
.ft CR
     None
.ft R
.fi
.SH DIAGNOSTICS
.sp
.TP
Tmax < Tmin;
.br
Tmax must exceed both Tmin1 and Tmin2
.SH RESTRICTIONS
.PP
None
.SH HISTORY
.TP
Oct 1999
Written by Danny Marks, ARS-NWRC, Boise, ID.
.TP
Oct 1999
Modified to calculate cloud cover factor rather than
attenuation factor by Adam Winstral, ARS-NWRC, Boise, ID.
.SH BUGS
.PP
None
.SH SEE ALSO
.TP
IPW
\fBdeltaT\fP,
\fBtcloud\fP
.PP
Bristow and Campbell 1984,
Runnind, Nemani, Hungerford 1987
