.TH "cnhist.all" "1" "5 November 2015" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBcnhist.all\fP - cumulative normalized histogram of set of IPW images
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBcnhist.all\fP [ \fB-m\fP \fImask\fP ] [\fIimage1\fP[,\fIimage2\fP,\fI...\fP]]
.ft R
.fi
.SH DESCRIPTION
.PP
\fBcnhist.all\fP calculates a cumulative normalized histogram of the
pixels in one or more images and writes the results in ASCII to
standard output in the following format:
.sp
.nf
.ft CR
        floating-value  percentile
.ft R
.fi
.SH OPTIONS
.TP
\fB-m\fP \fImask\fP
mask image
.SH OPERANDS
.TP
\fIimage1\fP[,\fIimage2\fP,...]
input image(s) (if only one image, defaults to standard input)
.sp
.SH EXAMPLES
.PP
To calculate normalized histograms of runoff from time-series images
of snowmelt over a season:
.sp
.nf
.ft CR
	cnhist -m basin_mask melt.01,melt.02,...melt.99 >cn.txt
.ft R
.fi

.PP
To graph the cumulative normalized histogram for a single image:
.sp
.nf
.ft CR
	cnhist.all -m basin_mask melt.50 | graph -a | plot
.ft R
.fi
.SH FILES
.PP
None.
.SH DIAGNOSTICS
.PP
None.
.SH RESTRICTIONS
.PP
Single-band input images only.
If multiple images are given, they must have the same #lines, #samps,
# bits, and the same floating-point quantization.
.SH HISTORY
.TP
Dec 1990
Written by Kelly Longley, Oregon State University,
Environmental Research Laboratory, Corvallis OR
.SH BUGS
.PP
None.
.SH SEE ALSO
.TP
IPW:
\fBcnhist\fP,
\fBhist\fP,
\fBhisteq\fP
.sp
.TP
UNIX:
graph, plot
.sp
.TP
GNU:
graph, xplot, gnuplot
