.TH "cnhist" "1" "11 June 1998" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBcnhist\fP - convert IPW histogram to cumulative normalized text file
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBcnhist\fP [\fIbegin \fP[\fIend\fP]]
.ft R
.fi
.SH DESCRIPTION
.PP
\fBcnhist\fP reads an IPW histogram image from the standard input and
writes a cumulative normalized histogram as text to the standard output.
If specified, only pixel values greater than or equal to \fIbegin\fP, and
less than or equal to \fIend\fP, will be considered.
.SH OPTIONS
.PP
None.
.SH OPERANDS
.TP
\fIbegin\fP
Begin processing at the input value with this index number
(default: 0).  The output values prior to this index number will be 0.
.sp
.TP
\fIend\fP
Cease processing after the input value with this index
number (default: last input value).  The remaining
output values will be 1.
.SH EXAMPLES
.PP
To view a cumulative histogram of "image":
.sp
.nf
.ft CR
	hist image | cnhist | graph -a | plot
.ft R
.fi
.SH FILES
.PP
None.
.SH DIAGNOSTICS
.PP
None.
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.TP
Jul 1990
Written by James Frew, UCSB
.SH BUGS
.PP
None.
.SH SEE ALSO
.TP
IPW:
\fBbtoa\fP,
\fBcnhist.all\fP,
\fBgrhist\fP,
\fBhist\fP,
\fBhisteq\fP,
\fBrmhdr\fP
.sp
.TP
UNIX:
awk, graph, plot
.sp
.TP
GNU:
graph, xplot
.PP
Frew 1990
.br
