.TH "ipw2xim" "1" "5 November 2015" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBipw2xim\fP - convert IPW image to xim format
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBipw2xim\fP [\fIimage\fP]
.ft R
.fi
.SH DESCRIPTION
.PP
\fBipw2xim\fP reads an IPW image (default: standard input) and writes it
it to the standard output in "xim" format.  An image in xim format
may be displayed in a X window by the xim or xxim commands.
.PP
Since xv and xloadimage support many more operations and formats
than the xim program, including modified versions of each that
support IPW images directly, \fBipw2xim\fP is archaic.  ipw2ppm will
convert images into the industry standard PPM format, including
support for color images.
.SH OPTIONS
.PP
None
.SH OPERANDS
.TP
[\fIimage\fP]
	image
.sp
.SH EXAMPLES
.PP
To display the IPW image "zot" in an X window:
.sp
.nf
.ft CR
	ipw2xim zot | xim
.ft R
.fi
.SH FILES
.sp
.nf
.ft CR
     None
.ft R
.fi
.SH DIAGNOSTICS
.sp
.TP
image must have 1 band
.br
	\fBipw2xim\fP supports only single band images.
.sp
.TP
band 0 has more than 256 levels per pixel
.br
	The xim format does not support more than 8 bits per color
.SH RESTRICTIONS
.PP
Color images are not currently supported.
.PP
xim and xxim automatically requantize their input (by dithering) to
the resolution of the X display device.
.SH HISTORY
.TP
Jul 1990
	Written by James Frew, UCSB.
.SH BUGS
.PP
None that we know of
.SH SEE ALSO
.TP
IPW
	\fBxim\fP,
\fBipw2ppm\fP
.TP
Image
	ximtoppm
