.TH "lqmm" "1" "10 April 1998" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBlqmm\fP - find minimum and maximum in LQ headers for set of IPW images
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBlqmm\fP \fIimage ...\fP
.ft R
.fi
.SH DESCRIPTION
.PP
\fBlqmm\fP returns the minimum and maximum values of the floating
point maps of all the given images.  The minimum and maximum are
output to the standard output.
.SH OPTIONS
.PP
None.
.SH OPERANDS
.TP
\fIimage ...\fP
input image(s)
.SH EXAMPLES
.PP
To get the min and max values of 24 hourly images of air temperature
so that they can all be quantized over the same range:
.sp
.nf
.ft CR
     lqmm img1 img2 img3 ... img24
.ft R
.fi
.SH FILES
.PP
None.
.SH DIAGNOSTICS
.PP
None.
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.TP
Jul 1990
Written by Kelly Longley, Oregon State University,
Environmental Research Laboratory, Corvallis OR
.SH BUGS
.PP
None.
.SH SEE ALSO
.TP
IPW:
\fBimgstat\fP,
\fBprhdr\fP,
\fBrequant\fP
