.TH "mkgeoh" "1" "5 March 2015" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBmkgeoh\fP - add a geodetic (GEO) header to an image
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBmkgeoh\fP \fB-o\fP \fIu\fP,\fIv\fP \fB-d\fP \fIdu\fP,\fIdv\fP \fB-u\fP \fIunits\fP \fB-c\fP \fIcsys\fP [ \fB-b\fP \fIband\fP[,\fI...\fP] ]
      [ \fB-f\fP ] [\fIimage\fP]
.ft R
.fi
.SH DESCRIPTION
.PP
\fBmkgeoh\fP constructs an IPW geodetic header (GEOH) and inserts it into
the headers of \fIimage\fP (default: standard input).  If the specified
bands already have GEO headers, they are overridden, and a warning
message is generated.
.PP
If the \fB-f option is specified, then only the headers are written to
the standard output, and any input image data is ignored.
.SH OPTIONS
.TP
\fB-o\fP \fIu\fP,\fIv\fP
The coordinates of image line 0 and sample 0 in \fIcsys\fP are
\fIu\fP and \fIv\fP, respectively.
.sp
.TP
\fB-d\fP \fIdu\fP,\fIdv\fP
The distances between adjacent image lines and samples in
\fIcsys\fP are \fIdu\fP and \fIdv\fP, respectively.
.sp
.TP
\fB-u\fP \fIunits\fP
\fIu\fP, \fIv\fP, \fIdu\fP, and \fIdv\fP are specified in \fIunits\fP (e.g.,
"meters", "km").
.sp
.TP
\fB-c\fP \fIcsys\fP
The geodetic coordinate system identifier is \fIcsys\fP (e.g.,
"UTM", "Lambert").  See the manual for
mkproj for a list
of standard names for coordinate systems.
.sp
.TP
\fB-b\fP \fIband\fP[,\fI...\fP]
The "geo" header will be applied only to the specified
\fIband\fPs (default: all bands).
.sp
.TP
\fB-f\fP
Force header output only.  Do not attempt to copy pixel
data from \fIimage\fP to the standard output.  Note that there
must still be at least an input BIH, and any input headers
(except superseded "geo" headers) will still be copied to
the standard output.
.SH OPERANDS
.TP
[\fIimage\fP]
input image (default: standard input)
.SH EXAMPLES
.PP
To create a "geo" header appropriate for a 5-meter grid located
in the Sierra Nevada, California:
.sp
.nf
.ft CR
	mkgeoh -c UTM -u meters -o 4051800,349350 -d -5,5
.ft R
.fi

.PP
Note the negative line spacing:  UTM northings run in the opposite
direction from IPW line numbers.
.SH FILES
.PP
None.
.SH DIAGNOSTICS
.TP
bad band number: \fIband\fP
A nonexistent input band was specified with \fB-b.
.sp
.TP
band \fIband\fP: replacing previous GEO header
Band \fIband\fP already had a "geo" header, which was replaced
by the newly-created one.
.SH RESTRICTIONS
.PP
There are not yet any standard identifiers for \fIcsys\fP and \fIunits\fP,
although some IPW programs such as gradient assume that any units
beginning with "m" are meters.  There is work underway to develop
standard \fIcsys\fP names.  See the IPW program \fBmkproj\fP.
.SH HISTORY
.TP
Jul 1990
Written by James Frew, UCSB.
.SH BUGS
.PP
None.
.SH SEE ALSO
.TP
IPW:
\fBmkproj\fP,
\fBreproj\fP,
\fBflip\fP,
\fBgradient\fP,
\fBhor1d\fP,
\fBhorizon\fP,
\fBmkbih\fP,
\fBprhdr\fP,
\fBrmhdr\fP,
\fBtranspose\fP,
\fBviewcalc\fP,
\fBwindow\fP,
\fBzoom\fP
.PP
Frew 1990
.br
