.TH "mkpcp" "1" "27 March 2009" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBmkpcp\fP - make precipitation files for 'snobal' command
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBmkpcp\fP
.ft R
.fi
.SH DESCRIPTION
.PP
\fBmkpcp\fP creates precipitation file for snobal(1).  The input
is:
.sp
.nf
.ft CR
	precip mass (kg/m^2),  precip temp (C)
.ft R
.fi

.PP
\fBmkpcp\fP calculates the precentage of the mass that's snow
based on the given temperature.  It also determines the snow's
density.  This is based on the following table:
.sp
.nf
.ft CR
	temperature		% snow	snow density
.ft R
.fi

.sp
.nf
.ft CR
	          T < -5 C	 100%	   75 kg/m^3
	  -5 C <= T < -3 C	 100%	  100 kg/m^3
	  -3 C <= T < -1.5 C	 100%	  150 kg/m^3
	-1.5 C <= T < -0.5 C	 100%	  175 kg/m^3
	-0.5 C <= T < 0 C	  75%	  200 kg/m^3
	   0 C <= T < 0.5 C	  25%	  250 kg/m^3
	 0.5 C <= T        	   0%	    0 kg/m^3
.ft R
.fi

.PP
Note:  \fBmkpcp\fP expects \fIprecip temp\fP, not air temperature.
Dewpoint temperature is the best estimate of \fIprecip temp\fP.
If air temperature is used all events occuring at temperatures
of +0.5 and above will be assumed to be rain.
.PP
\fBmkpcp\fP outputs the following to the standard output:
.sp
.nf
.ft CR
	precip mass (kg/m^2) % snow (0.0 to 1.0) snow density (kg/m^3) precip temp (C)
.ft R
.fi

.PP
This output file is close to the format snobal expects for its
precipitation images; the time since the start of the model run
must still be added.
.SH OPTIONS
.PP
none
.SH OPERANDS
.PP
none
.SH EXAMPLES
.PP
none
.SH FILES
.PP
none
.SH DIAGNOSTICS
.PP
none
.SH RESTRICTIONS
.PP
none
.SH HISTORY
.TP
Sep 1999
written by D. Marks, NWRC, USDA-ARS
.SH BUGS
.PP
none
.SH SEE ALSO
.TP
IPW:
\fBisnobal\fP,
\fBmkprecip\fP,
\fBsnobal\fP,
.PP
Marks 1998,
Marks 1999a,
Susong 1999
