.TH "mult" "1" "5 March 2015" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBmult\fP - perform multiplication or division on pixels (DEPRECIATED)
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBmult\fP [ \fB-n\fP \fInbits\fP ] [ \fB-r\fP \fIband\fP,... ] [ \fIimage\fP ]
.ft R
.fi
.SH DESCRIPTION
.PP
\fBmult\fP reads a multi-band \fIimage\fP and
writes the product of its bands to the standard output.  For
each input sample, the corresponding output sample is:
.sp
.nf
.ft CR
	p[0] * p[1] * ... * p[nbands-1]
.ft R
.fi

.PP
where \fIp\fP is the input pixel value and \fInbands\fP is the number
of input bands.
.PP
To effect division, specified bands are converted to reciprocals
before multiplication.  Zeroes in the denominator are replaced by
ones.
.SH OPTIONS
.TP
\fB-n\fP \fInbits\fP
Use \fInbits\fP bits per output pixel (default: maximum number
of bits per input pixel).
.sp
.TP
\fB-r\fP \fIband\fP,...
Use the reciprocal of the pixel value in the specified
bands.  To avoid division by 0, any 0 values in the
specified bands will be set to 1.
.SH OPERANDS
.TP
\fIimage\fP
multi-band input image (default: standard input)
.SH EXAMPLES
.PP
To multiply two single-band images together:
.sp
.nf
.ft CR
        mux image1 image2 | mult
.ft R
.fi

.PP
To divide the first band of a 2-band image by the second band
(i.e. band0 / band1 ):
.sp
.nf
.ft CR
        mult -r 1
.ft R
.fi
.SH FILES
.PP
None.
.SH DIAGNOSTICS
.TP
\fB-r \fIband\fP: not that many bands
A nonexistent input band was specified with \fB-r.
.SH NOTES
.PP
This command has been DEPRECIATED because its functionality
is provided by the command \fBimath\fP.
This command may be removed in future versions of IPW.
.SH HISTORY
.TP
Jul 1990
Written by James Frew, UCSB.
.sp
.TP
Mar 1993
Fixed to not blow up on constant surface outputs
(i.e., when multiplying by value 0 images),
Dana Jacobsen, ERL-C.
.sp
.TP
Apr 1993
Ran through Purify.  Dana Jacobsen, ERL-C.
.sp
.TP
Oct 1993
Multiplies are done in double precision.
Dana Jacobsen, ERL-C.
.SH SEE ALSO
.TP
IPW:
\fBimath\fP,
\fBdemux\fP,
\fBmux\fP,
\fBiadd\fP,
\fBlincom\fP,
\fBscale\fP
.PP
Frew 1990
