.TH "normalize" "1" "5 March 2015" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBnormalize\fP - normalize image bands
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBnormalize\fP [ \fB-b\fP \fIbits\fP ] [ \fIimage\fP ]
.ft R
.fi
.SH DESCRIPTION
.PP
\fBnormalize\fP reads a multi-band image and
outputs a multi-band image in which the sum of all bands is a surface
with value 1.0 everywhere (within the available image precision).
.PP
When all bands of an input pixel are 0.0, the program will
output zeros (i.e. these output pixels will not sum to 1.0).
.PP
NOTE:  This program is very sensitive to quantization error.  The
larger the number of image bits used, the closer the sum of the
output bands gets to 1.0.
.SH OPTIONS
.TP
\fB-b\fP \fIbits\fP
Use \fIbits\fP bits per output pixel (default: 16).
.SH OPERANDS
.TP
\fIimage\fP
multi-band input image (default: standard input)
.SH EXAMPLES
.SH FILES
.PP
None.
.SH DIAGNOSTICS
.PP
None.
.SH RESTRICTIONS
.PP
The image must have more than one band.
.SH HISTORY
.TP
Dec 1993
Started by Paul Hardin, ERL-C.
.sp
.TP
Aug 1994
Working version completed by Rusty Dodson, ERL-C.
.SH BUGS
.PP
None.
.SH SEE ALSO
.TP
IPW:
\fBdemux\fP,
\fBmux\fP,
\fBiadd\fP
