.TH "pmx" "1" "10 April 1998" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBpmx\fP - latent heat flux (LE) using simplified Penman-Monteith method
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBpmx\fP
.ft R
.fi
.SH DESCRIPTION
.PP
\fBpmx\fP calculates LE flux (W/m2, +/-) using a simplified form of
the Penman-Monteith combination approach. Inputs are as follows:
.sp
.nf
.ft CR
        ta, ea, u, Rn, lai, cond
.ft R
.fi

.sp
.nf
.ft CR
        ta     = air temperature  (C)
        ea     =  actual vapor pressure at ta (Pa)
        u      = wind speed (m/s)
        Rn     = net radiation (W/m2, +/-)
        lai    = projected (1-sided) leaf area index
        cond   = bulk canopy conductivity (m/s)
.ft R
.fi

.PP
Assumptions: No stability correction, G is estimated,
canopy height and z0 are a function of lai.  Use with
daily data.
.SH OPTIONS
.PP
none
.SH OPERANDS
.PP
none
.SH EXAMPLES
.PP
none
.SH FILES
.PP
none
.SH DIAGNOSTICS
.PP
none
.SH RESTRICTIONS
.PP
none
.SH HISTORY
.TP
Jun 1993
written by J. Kimball, OSU, EPA-ERL.
.TP
Oct 1993
modified \fBpmx\fP by adding a stability function for
the calculation of aerodynamic resistance based on a
bulk Richardson number.
.TP
Oct 1994
made \fBpmx\fP more generalizeable.
.TP
Jun 1995
Converted to IPW by J. Domingo, OSU, EPA NHEERL/WED
.SH BUGS
.PP
none
.SH SEE ALSO
.TP
IPW:
    \fBbowvap\fP,
\fBpenmanx\fP,
\fBipmx\fP,
\fBptaylorx\fP,
\fBiptx\fP,
\fBptx\fP,
\fBtrb_Ri\fP,
\fBitrbxfr\fP,
\fBtrbxfr\fP
.PP
Brutsaert 1982,
Mahrt, Ek 1984,
Monteith, Unsworth 1990,
Pereira, Nova 1992,
Priestley, Taylor, 1972,
Running, Coughlan 1988,
Stewart 1984
