.TH "randomize" "1" "5 November 2015" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBrandomize\fP - randomly shuffle lines of an IPW image
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBrandomize\fP [ \fB-s\fP \fIseed\fP ] [\fIimage ...\fP]
.ft R
.fi
.SH DESCRIPTION
.PP
\fBrandomize\fP copies lines from \fIimage\fPs (default: standard input) and
writes to the standard output, arranging the lines in random order.
.PP
An image name of '-' means the standard input.
.SH OPTIONS
.TP
\fB-s\fP \fIseed\fP
A seed value of \fIseed\fP will be given to random, producing
repeatable output (default: no seed).
.SH OPERANDS
.TP
\fIimage ...\fP
input image(s) to be scrambled
.SH EXAMPLES
.PP
To produce a scrambled version of \fIfile\fP:
.sp
.nf
.ft CR
     randomize file
.ft R
.fi
.SH FILES
.PP
None.
.SH DIAGNOSTICS
.TP
# of values must be > 0
There must be at least one line of input.
.SH RESTRICTIONS
.PP
None
.SH HISTORY
.TP
May 1988
Written by James Frew, UCSB.
.TP
Apr 1993
Added \fB-s option.  Allowed to read images on the command
line as well as from standard input.
Dana Jacobsen, ERL-C.
.TP
Aug 1997
Converted to IPW Version 2.0, D. Marks, USGS, ERL-c
.SH BUGS
.PP
None
.SH SEE ALSO
.TP
IPW:
\fBrandom\fP,
\fBwedge\fP
.TP
UNIX:
wc, paste, sort, sed
