.TH "random" "1" "5 March 2015" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBrandom\fP - generate random values
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBrandom\fP \fB-n\fP \fInlines\fP \fB-r\fP \fImin\fP,\fImax\fP[,\fI...\fP] [ \fB-p\fP \fIprecision\fP ]
      [ \fB-s\fP \fIseed\fP ]
.ft R
.fi
.SH DESCRIPTION
.PP
Random prints columns of \fBrandom\fP values in the range specified as
ASCII text to the standard output.  One column is printed for each
min,max pair specified.
.SH OPTIONS
.TP
\fB-n\fP \fInlines\fP
Print \fInlines\fP lines of output.
.sp
.TP
\fB-r\fP \fImin\fP,\fImax\fP[,\fI...\fP]
Output values will range between \fImin\fP and \fImax\fP inclusive.
Each \fImin\fP,\fImax\fP pair will control an output column.
.PP
Both \fB-n and \fB-r must be specified.
.TP
\fB-p\fP \fIprecision\fP
Print output values using \fIprecision\fP digits of precision
(default: 0, meaning round to nearest integer).
.sp
.TP
\fB-s\fP \fIseed\fP
Initialize the \fBrandom\fP number generator with \fIseed\fP
(default: obtain seed from system clock).  This option can
be used to obtain the same output from multiple invocations
of \fBrandom\fP.
.SH OPERANDS
.PP
	None
.PP
.SH EXAMPLES
.PP
The command:
.sp
.nf
.ft CR
	random -n 5 -r 0,10,0,10
.ft R
.fi

.PP
yields something like:
.sp
.nf
.ft CR
	7 1
	5 8
	7 2
	1 8
	0 2
.ft R
.fi

.PP
To obtain the values of 100 randomly selected pixels from a
512 line by 512 sample "image":
.sp
.nf
.ft CR
	random -n 100 -r 0,511,0,511 | sort -n | primg -i image
.ft R
.fi

.PP
Note that the \fBrandom\fP coordinates must be sorted before being
passed to primg.
.SH FILES
.sp
.nf
.ft CR
     None
.ft R
.fi
.SH DIAGNOSTICS
.sp
.TP
# of values must be > 0
.br
	\fInlines\fP must be a positive, non-zero integer.
.sp
.TP
range(s) must be specified by min,max pairs
.br
	\fB-r must have an even number of arguments
.sp
.TP
output precision must be >= 0
.br
	\fIprecision\fP must be a positive integer.
.SH RESTRICTIONS
.PP
\fBrandom\fP uses the \fBrandom\fP(3) functions from 4.3 BSD UNIX.  The source
for these functions is normally included with IPW.
.SH HISTORY
.TP
Jul 1990
	Written by James Frew, UCSB.
Base IPW routine (Frew, 1990)
.SH BUGS
.PP
None that we know of
.SH SEE ALSO
.TP
IPW
	\fBprimg\fP
.TP
UNIX
	random, sort
.PP
Frew, J., 1990.  The Image Processing Workbench.  Ph.D. Thesis,
	Department of Geography, University of California, Santa
	Barbara, CA, 382pp.
