.TH "rmsd" "1" "5 March 2015" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBrmsd\fP - computes model fitting statistics  RMSD, ME, and MBD
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBrmsd\fP
.ft R
.fi
.SH DESCRIPTION
.PP
\fBrmsd\fP reads an X-Y vector pair (X = "measured".
Y = "modeled") from the standard input and computes
root mean square difference (RMSD), model efficiency (ME),
and mean bias difference (MBD). (Note that RMSD and MBD are
considered "difference" rather than "error" statistics because
there is generally a significant uncertainty in the measured
parameter which makes it difficult to assume that difference
between the "modeled" and "measured" value is an error.)
A small RMSD and MBD shows a good "fit" between the vectors,
as does a ME value approaching 1.0.
.SH OPTIONS
.PP
None
.SH OPERANDS
.PP
None.
.SH EXAMPLES
.PP
The following input:
.sp
.nf
.ft CR
	 0  1
	 2  3
	 4  5
	 6  7
	 8  9
	10 11
.ft R
.fi

.PP
produces the following output:
.sp
.nf
.ft CR
	n =  6
	mean =  5
	Model Efficiency, ME 0.914286
	RMSD 1
	Mean Bias Difference, MBD 1
.ft R
.fi
.SH FILES
.PP
None
.SH DIAGNOSTICS
.sp
.TP
input line must have exactly 2 fields
.SH RESTRICTIONS
.PP
None
.SH HISTORY
.TP
Oct 2001
	Written by D. Marks, ARS-NWRC, Boise, ID.
.SH BUGS
.PP
None
.SH SEE ALSO
.TP
IPW
.TP
UNIX
\fBawk\fP
.PP
Frew 1990,
Green and Stepheson 1986,
Marks 1999a,
Nash and Sutcliffe 1970
