.TH "stoporad" "1" "8 June 2015" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBstoporad\fP - topographically-corrected solar radiation over snow
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBstoporad\fP [ \fB-n\fP ] [ \fB-z\fP \fIelev\fP ] [ \fB-t\fP \fItau\fP ] [ \fB-w\fP \fIomega\fP ] [ \fB-g\fP \fIgfact\fP ]
     \fB-x\fP \fIw1,w2\fP \fB-s\fP \fIstart\fP \fB-d\fP \fIday\fP \fB-f\fP \fIzone\fP \fB-y\fP \fIyear\fP
     [ \fB-b\fP \fId,m,s\fP \fB-l\fP \fId,m,s\fP ] [ \fB-A\fP \fImu,azm\fP ]
     \fB-a\fP \fIgsize\fP \fB-m\fP \fImaxgsz\fP \fB-c\fP \fIdirt\fP
     [ \fB-r\fP \fIerad_image\fP ] [ \fB-k\fP \fIalb_image\fP ] [ \fB-D\fP ]  [ \fIimage\fP ]
.ft R
.fi
.SH DESCRIPTION
.PP
\fBstoporad\fP is part of a family of radiation transfer simulation,
and solar/terrain geometry calculation tools, derived from the
programs and tools developed at UCSB by Jeff Dozier, Jim Frew, and
Ralph Dubayah.  Most of the modified programs were originally built
Kelly Longley, OSU, ERL-C
.PP
\fBstoporad\fP is a script that calls salbedo and toporad, to simulate
topographic radiation over snow-covered terrain. All of the snowcover
radiation transfer tools are designated by the "s" prefix in front of
the standard tool's name.
.PP
\fBstoporad\fP is the snow cover version of the program toporad.
\fBstoporad\fP computes solar radiation over a topographic grid over snow,
using a two-stream atmospheric radiation model.
If the sun is below the horizon at the specified time, a message is
printed to the screen and no output image is generated.
.PP
Surface albedo is calculated by program salbedo for input to toporad.
If the -k option is specified, the intermediate calculation of albedo
is saved in the specified image file.
R0, reflectance of the substrate is set as the mean surface albedo.
.PP
If a beam & diffuse radiation image is specified with the -r option
then salbedo is not called, and elev, tau, omega, and gfact parameters
are not required.
.PP
Input water year days are assumed to be in GMT unless the -f (time
zone conversion: minutes west of Greenwich) option is specified.
.SH OPTIONS
.TP
\fB-n\fP
net radiation instead of incoming
.sp
.TP
\fB-z\fP \fIelev\fP
elevation of optical depth measurement
.sp
.TP
\fB-t\fP \fItau\fP
optical depth at z
.sp
.TP
\fB-w\fP \fIomega\fP
single-scattering albedo
.sp
.TP
\fB-g\fP \fIgfact\fP
scattering asymmetry parameter
.sp
.TP
\fB-x\fP \fIw1\fP,\fIw2\fP
wavelength range, micrometers (.28,.7 for vis; .7,2.8 for IR)
.sp
.TP
\fB-s\fP \fIstart\fP
scalar day of last snow storm or IPW image containing distributed day of last snow storm (water year day)
.sp
.TP
\fB-d\fP \fIday\fP
current day (water year day)
.sp
.TP
\fB-f\fP \fIzone\fP
time zone conversion (minutes west of Greenwich)
.sp
.TP
\fB-y\fP \fIyear\fP
water year
.sp
.TP
\fB-b\fP \fId,m,s\fP
latitude (degrees, minutes, seconds)
.sp
.TP
\fB-l\fP \fId,m,s\fP
longitude (degrees, minutes, seconds)
.sp
.TP
\fB-A\fP \fImu,azm\fP
sun angles, i.e., zenith and azimuth angles of the sun's position as
outputed by \fBsunang\fP.  \fImu\fP is cosine of the zenith angle, and
\fIazm\fP is the azimuth angle in degrees.
.PP
If the latitude and longitude is not specified with the \fB-b\fP and
\fB-l\fP options, then the sun angle must be specified with the \fB-A\fP
option.
.TP
\fB-a\fP \fIgsize\fP
grain size for albedo calculation
.sp
.TP
\fB-m\fP \fImaxgsz\fP
maximum grain size
.sp
.TP
\fB-c\fP \fIdirt\fP
contaimination factor for visible albedo
.sp
.TP
\fB-r\fP \fIerad_image\fP
2-band image containing beam & diffuse radiation (output from elevrad)
.sp
.TP
\fB-k\fP \fIalb_image\fP
keep albedo calculation in specified file
.sp
.TP
\fB-D\fP
output diffuse radiation along with the global radiation
.SH OPERANDS
.TP
\fIimage\fP
The input image file has five bands in this order:
.sp
.nf
.ft CR
     band 0 : elevation
      "   1 : slope
      "   2 : azimuth
      "   3 : sky view factor
      "   4 : terrain configuration factor
.ft R
.fi

.sp
(default: standard input).
.SH EXAMPLES
.PP
To calculate visible, topographically distributed radiation, over
the Park City, Utah, area, for noon, March 1, 1995, saving
the albedo file:
.sp
.nf
.ft CR
     stoporad -z 100 -t 0.2 -w 0.85 -g 0.3 -x .28,.7 -s 139 \\
          -d 150.500 -f 420 -y 1995 -b 40,37,12.6 \\
          -l -111,31,58.2 -a 75 -m 1000 -c 1 \\
          -k albedo.150.5 infile.150.5 > outfile.150.5
.ft R
.fi
.SH FILES
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.TP
Oct 1990
Written by Kelly Longley, Oregon State University,
Environmental Protection Agency Laboratory, Corvallis OR
.sp
.TP
Dec 1990
Added option for running elevrad separately,
by K. Longley, OSU, EPA ERL-C
.sp
.TP
May 1991
Added option to keep albedo images,
by K. Longley, OSU EPA ERL-C
.sp
.TP
Nov 1998
Added the options to specify solar angles and to output diffuse
radiation.  J. Domingo, OSU
.SH SEE ALSO
.TP
IPW
	\fBstandard stoporad\fP,
\fBlocally modified toporad\fP,
\fBalbedo\fP,
\fBelevrad\fP,
\fBialbedo\fP,
\fBselevrad\fP,
\fBtoporad\fP
.PP
Dozier, J., 1980.  "A clear-sky spectral solar radiation model for
	snow-covered mountainous terrain".  Water Resources Research,
	vol. 16, pp. 709-718.
.PP
Dozier, J., and J. Frew, 1981.  "Atmospheric corrections to satellite
	radiometric data over rugged terrain".  Remote Sensing of
	Environment, vol. 11, pp. 191-205.
.PP
Dozier, J., J. Bruno, and P. Downey, 1991.  "A faster solution to the
	horizon problem", Computers and Geosciences, volume 7,
	number 2, pp. 145-151.
.PP
Dozier, J., and J. Frew, 1990.  Rapid calculation of terrain parameters
	for radiation modeling from digital elevation data". IEEE
	Transactions on Geoscience and Remote Sensing, vol. 28, no. 5,
	pp. 963-969.
.PP
Dubayah, R., 1994.  "Modeling a solar radiation topoclimatology for the
	Rio Grande River Basin".  Journal of Vegetation Science, vol. 5,
	pp. 627-640.
.TH "stoporad" "1" "8 June 2015" "IPW v2" "IPW User Commands"
.SH NAME
.PP
\fBstoporad\fP - topographically-corrected solar radiation over snow
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBstoporad\fP [ \fB-n\fP ] [ \fB-z\fP \fIelev\fP ] [ \fB-t\fP \fItau\fP ] [ \fB-w\fP \fIomega\fP ] [ \fB-g\fP \fIgfact\fP ]
     \fB-x\fP \fIw1,w2\fP \fB-s\fP \fIstart\fP \fB-d\fP \fIday\fP \fB-f\fP \fIzone\fP \fB-y\fP \fIyear\fP
     [ \fB-b\fP \fId,m,s\fP \fB-l\fP \fId,m,s\fP ] [ \fB-A\fP \fImu,azm\fP ]
     \fB-a\fP \fIgsize\fP \fB-m\fP \fImaxgsz\fP \fB-c\fP \fIdirt\fP
     [ \fB-r\fP \fIerad_image\fP ] [ \fB-k\fP \fIalb_image\fP ] [ \fB-D\fP ]  [ \fIimage\fP ]
.ft R
.fi
.SH DESCRIPTION
.PP
\fBstoporad\fP is part of a family of radiation transfer simulation,
and solar/terrain geometry calculation tools, derived from the
programs and tools developed at UCSB by Jeff Dozier, Jim Frew, and
Ralph Dubayah.  Most of the modified programs were originally built
Kelly Longley, OSU, ERL-C
.PP
\fBstoporad\fP is a script that calls salbedo and toporad, to simulate
topographic radiation over snow-covered terrain. All of the snowcover
radiation transfer tools are designated by the "s" prefix in front of
the standard tool's name.
.PP
\fBstoporad\fP is the snow cover version of the program toporad.
\fBstoporad\fP computes solar radiation over a topographic grid over snow,
using a two-stream atmospheric radiation model.
If the sun is below the horizon at the specified time, a message is
printed to the screen and no output image is generated.
.PP
Surface albedo is calculated by program salbedo for input to toporad.
If the -k option is specified, the intermediate calculation of albedo
is saved in the specified image file.
R0, reflectance of the substrate is set as the mean surface albedo.
.PP
If a beam & diffuse radiation image is specified with the -r option
then salbedo is not called, and elev, tau, omega, and gfact parameters
are not required.
.PP
Input water year days are assumed to be in GMT unless the -f (time
zone conversion: minutes west of Greenwich) option is specified.
.SH OPTIONS
.TP
\fB-n\fP
net radiation instead of incoming
.sp
.TP
\fB-z\fP \fIelev\fP
elevation of optical depth measurement
.sp
.TP
\fB-t\fP \fItau\fP
optical depth at z
.sp
.TP
\fB-w\fP \fIomega\fP
single-scattering albedo
.sp
.TP
\fB-g\fP \fIgfact\fP
scattering asymmetry parameter
.sp
.TP
\fB-x\fP \fIw1\fP,\fIw2\fP
wavelength range, micrometers (.28,.7 for vis; .7,2.8 for IR)
.sp
.TP
\fB-s\fP \fIstart\fP
scalar day of last snow storm or IPW image containing distributed day of last snow storm (water year day)
.sp
.TP
\fB-d\fP \fIday\fP
current day (water year day)
.sp
.TP
\fB-f\fP \fIzone\fP
time zone conversion (minutes west of Greenwich)
.sp
.TP
\fB-y\fP \fIyear\fP
water year
.sp
.TP
\fB-b\fP \fId,m,s\fP
latitude (degrees, minutes, seconds)
.sp
.TP
\fB-l\fP \fId,m,s\fP
longitude (degrees, minutes, seconds)
.sp
.TP
\fB-A\fP \fImu,azm\fP
sun angles, i.e., zenith and azimuth angles of the sun's position as
outputed by \fBsunang\fP.  \fImu\fP is cosine of the zenith angle, and
\fIazm\fP is the azimuth angle in degrees.
.PP
If the latitude and longitude is not specified with the \fB-b\fP and
\fB-l\fP options, then the sun angle must be specified with the \fB-A\fP
option.
.TP
\fB-a\fP \fIgsize\fP
grain size for albedo calculation
.sp
.TP
\fB-m\fP \fImaxgsz\fP
maximum grain size
.sp
.TP
\fB-c\fP \fIdirt\fP
contaimination factor for visible albedo
.sp
.TP
\fB-r\fP \fIerad_image\fP
2-band image containing beam & diffuse radiation (output from elevrad)
.sp
.TP
\fB-k\fP \fIalb_image\fP
keep albedo calculation in specified file
.sp
.TP
\fB-D\fP
output diffuse radiation along with the global radiation
.SH OPERANDS
.TP
\fIimage\fP
The input image file has five bands in this order:
.sp
.nf
.ft CR
     band 0 : elevation
      "   1 : slope
      "   2 : azimuth
      "   3 : sky view factor
      "   4 : terrain configuration factor
.ft R
.fi

.sp
(default: standard input).
.SH EXAMPLES
.PP
To calculate visible, topographically distributed radiation, over
the Park City, Utah, area, for noon, March 1, 1995, saving
the albedo file:
.sp
.nf
.ft CR
     stoporad -z 100 -t 0.2 -w 0.85 -g 0.3 -x .28,.7 -s 139 \\
          -d 150.500 -f 420 -y 1995 -b 40,37,12.6 \\
          -l -111,31,58.2 -a 75 -m 1000 -c 1 \\
          -k albedo.150.5 infile.150.5 > outfile.150.5
.ft R
.fi
.SH FILES
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.TP
Oct 1990
Written by Kelly Longley, Oregon State University,
Environmental Protection Agency Laboratory, Corvallis OR
.sp
.TP
Dec 1990
Added option for running elevrad separately,
by K. Longley, OSU, EPA ERL-C
.sp
.TP
May 1991
Added option to keep albedo images,
by K. Longley, OSU EPA ERL-C
.sp
.TP
Nov 1998
Added the options to specify solar angles and to output diffuse
radiation.  J. Domingo, OSU
.SH SEE ALSO
.TP
IPW
	\fBstandard stoporad\fP,
\fBlocally modified toporad\fP,
\fBalbedo\fP,
\fBelevrad\fP,
\fBialbedo\fP,
\fBselevrad\fP,
\fBtoporad\fP
.PP
Dozier, J., 1980.  "A clear-sky spectral solar radiation model for
	snow-covered mountainous terrain".  Water Resources Research,
	vol. 16, pp. 709-718.
.PP
Dozier, J., and J. Frew, 1981.  "Atmospheric corrections to satellite
	radiometric data over rugged terrain".  Remote Sensing of
	Environment, vol. 11, pp. 191-205.
.PP
Dozier, J., J. Bruno, and P. Downey, 1991.  "A faster solution to the
	horizon problem", Computers and Geosciences, volume 7,
	number 2, pp. 145-151.
.PP
Dozier, J., and J. Frew, 1990.  Rapid calculation of terrain parameters
	for radiation modeling from digital elevation data". IEEE
	Transactions on Geoscience and Remote Sensing, vol. 28, no. 5,
	pp. 963-969.
.PP
Dubayah, R., 1994.  "Modeling a solar radiation topoclimatology for the
	Rio Grande River Basin".  Journal of Vegetation Science, vol. 5,
	pp. 627-640.
