.TH "usage" "1" "5 March 2015" "IPW v2" "IPW Shell-Library Commands"
.SH NAME
.PP
\fBusage\fP - standard IPW usage message for shell scripts
.SH SYNOPSIS
.sp
.nf
.ft CR
\fBusage\fP \fIpgm\fP \fIsynopsis\fP \fIdescription\fP
.ft R
.fi
.SH DESCRIPTION
.PP
\fBusage\fP is a usage message generator that may be called by IPW shell
scripts.  The usage messages are printed in a similar format to the
IPW usage message standard for C programs.
.SH OPTIONS
.PP
None.
.SH OPERANDS
.TP
\fIpgm\fP
Name of program that generated the usage message.
.TP
\fIsysnopsis\fP
String explaining how the program is called.
.TP
\fIdescription\fP
Description of the program.
.SH EXAMPLES
.sp
.nf
.ft CR
    \fBusage\fP $0 'foo -n integer [ file ]' 'frobnicates a file'
.ft R
.fi
.SH FILES
.PP
None.
.SH DIAGNOSTICS
.PP
Always exits with nonzero status.
