.TH "rmtrail" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBrmtrail\fP - remove trailing white space from string
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

void
rmtrail(
	char *s)

.ft R
.fi
.SH DESCRIPTION
.PP
Rmtrail writes an EOS after the last (i.e., rightmost) non-blank
character in "s".
.SH RETURN VALUE
.PP
None.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
