.TH "g_snow" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBg_snow\fP - conduction heat flow between two snow layers
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"
#include "snow.h"

double
g_snow(
     double  rho1,  /* upper snow layer's density (kg/m^3)  */
     double  rho2,  /* lower  "     "        "    (kg/m^3)  */
     double  ts1,   /* upper snow layer's temperature (K)   */
     double  ts2,   /* lower  "     "         "       (K)   */
     double  ds1,   /* upper snow layer's thickness (m)     */
     double  ds2,   /* lower  "     "         "     (m)     */
     double  pa)    /* air pressure (Pa)                    */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBg_snow\fP calculates the heat flow between two snow layers
for both conduction and vapor transport.  See pages 46 and 47
of the reference below.
.SH RETURN VALUE
.PP
heat transfer between snow layers (J/m^2)
.SH HISTORY
.TP
Aug 1986
written by D. Marks, CSL, UCSB;
.sp
.TP
May 1995
Converted to IPW by J. Domingo, OSU
.SH SEE ALSO
.PP
Anderson 1976
.br
