.TH "set_lqh" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBset_lqh\fP - set LQ headers for all bands of image
.SH SYNOPSIS
.SH DESCRIPTION
.SH RETURN VALUE
.PP
None.
.SH EXAMPLES
.SH GLOBALS READ
.PP
None.
.SH GLOBALS MODIFIED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
