.TH "pxclose" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBpxclose\fP - close pixel I/O file descriptor
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "pixio.h"

int
pxclose(
	int		fd)	|* file descriptor		*|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBpxclose\fP resets all pixel I/O information associated with file
descriptor fd, then calls uclose to close the associated file.
.PP
Call \fBpxclose\fP if you need to reclaim a file descriptor that has been
read|written by pvread|pvwrite.
.SH RETURN VALUE
.PP
OK for success, ERROR for failure
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_piocb
.SH DIAGNOSTICS
.SH RESTRICTIONS
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
