.TH "delsv" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBdelsv\fP - delete i'th string from strvec
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

STRVEC_T *
delsv(
	REG_1 STRVEC_T *p,
	REG_2 int       i)

.ft R
.fi
.SH DESCRIPTION
.PP
\fBdelsv\fP deletes the i'th string from strvec p.
.PP
There is no error indication if the i'th string doesn't exist -- \fBdelsv\fP
just returns.
.SH RETURN VALUE
.PP
p
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
