.TH "ltoi" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBltoi\fP - convert long int to int
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

int
ltoi(
	long            i)	/* long to be converted to int	 */

.ft R
.fi
.SH DESCRIPTION
.PP
\fBltoi\fP converts its long argument to an int.  If the long integer
value won't fit in an
int, execution terminates with an IPW error message.
.PP
\fBltoi\fP is useful for converting long values in IPW image headers into
ints for use in loops, subscripts, etc., without generating scads of
superfluous "lint" warnings.
.SH RETURN VALUE
.PP
The int equivalent of "i" is returned.
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.sp
.TP
<i> won't fit in an "int"
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
