.TH "ubof" "3" "10 April 1998" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBubof\fP - check for UIO beginning-of-file
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

bool_t
ubof(
	int             fd)	|* file descriptor		 *|

.ft R
.fi
.SH DESCRIPTION
.PP
\fBubof\fP tests whether any I/O has been performed on file descriptor fd
since it was last u[rw]opened, i.e., are we at the Beginning Of
the File?
.PP
\fBubof\fP exists mainly to allow the hrname to reset itself after a file
descriptor has been closed and reopened.  \fBubof\fP will probably not need
to be called by IPW application programs.
.SH RETURN VALUE
.PP
TRUE	no I/O has been performed (i.e., at beginning of file)
.PP
FALSE	I/O has been performed (not at beginning of file)
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
_uiocb
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
