.TH "yearday" "3" "5 March 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fByearday\fP - returns the yearday (day of year) for a given date
.SH SYNOPSIS
.sp
.nf
.ft CR
#include "ipw.h"

int
yearday(
	int 	year,		|* e.g., 1997		*|
	int 	month,		|* [1 - 12]		*|
	int 	day)		|* [1 - 31]		*|

.ft R
.fi
.SH DESCRIPTION
.PP
\fByearday\fP returns the \fByearday\fP for the given date.  \fByearday\fP is
the 'day of the year', sometimes called (incorrectly) 'julian day'.
.SH RETURN VALUE
.PP
1 - 366
.SH EXAMPLES
.SH GLOBALS ACCESSED
.PP
None.
.SH DIAGNOSTICS
.SH RESTRICTIONS
.PP
None.
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
