.TH "uwopen_temp" "3" "5 November 2015" "IPW v2" "IPW Library Functions"
.SH NAME
.PP
\fBuwopen_temp\fP - create a temporary UNIX file and open it for writing
.SH SYNOPSIS
.sp
.nf
.ft CR
int
uwopen_temp(char * template)	|* template for file name *|
.ft R
.fi
.SH DESCRIPTION
.PP
\fBuwopen_temp\fP creates a temporary file by passing the given filename template
to the Standard C library function mkstemp().  The template should be created
by calling the mktemplate() function.
mkstemp() generates a filename in the template itself, opens the file for
writing, and returns the new file descriptor.  uwopen_temp then initializes the
file descriptor for IPW I/O.
.SH RETURN VALUE
.PP
>= 0	A writable UNIX file descriptor for successful open.
.PP
ERROR	Error occurred.
.SH EXAMPLES
.PP
Typical usage:
.sp
.nf
.ft CR
    char * template;
    template = mktemplate("foo");
    if (template == NULL)
        error("Unable to create template for temporary file");
    int fdt;
    fdt = uwopen_temp(template);
    ...
    uclose(fdt);
    SAFE_FREE(template);
.ft R
.fi
.SH GLOBALS ACCESSED
.SH DIAGNOSTICS
.SH RESTRICTIONS
.SH HISTORY
.SH BUGS
.PP
None.
.SH SEE ALSO
.TP
IPW:
mktemplate(),
uwopen()
